<?php
    /** @var Ubertheme\UbContentSlider\Block\Slider $block */

    /** @var Magento\Catalog\Helper\Output $catalogHelper */
    $catalogHelper = $this->helper('Magento\Catalog\Helper\Output');

    /** @var Ubertheme\UbContentSlider\Helper\Data $blockHelper */
    $blockHelper = $this->helper('Ubertheme\UbContentSlider\Helper\Data');

    $type = 'widget-product-grid';
    $mode = 'grid';
    $showWishlist = $config->show_wishlist;
    $showCompare = $config->show_compare;
    $showCart = $config->show_add_cart;
    $classes = "block widget block-products-list";
    $classes .= " {$mode} {$config->addition_class} ub-content-slider-block {$config->content_type}";
    if (!$config->show_title) {
        $classes .= " no-title";
    }

?>

<div class="<?= $classes; ?>">

    <?php if ($config->show_title): ?>
    <div class="block-title">
        <strong> <?php echo $block->escapeHtml($config->title); ?> </strong>
    </div>
    <?php endif; ?>

    <?php if ($items->getSize()): ?>

    <!--Slider content-->
    <div class="block-content">
        <div class="products-grid grid">
            <div class="product-items <?php echo $type; ?> owl-carousel owl-theme" data-mage-init='{"ubOwlCarousel1": <?php echo $block->getOwl1JsonConfigs()?>}'>
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_product): ?>
                    <?php
                        //Load product data model for bestsellers products case only
                        if ($config->content_type == 'bestseller_products') {
                            $productData = $_product->getData();
                            $productId = isset($productData['product_id']) ? $productData['product_id'] : null;
                            $_product = $block->loadProductById($productId);
                        }
                    ?>
                    <?php if ($_product) : ?>
                        <?php echo ($iterator++ == 1) ? '<div class="product-item">' : '</div><div class="product-item">' ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            $imageId = ($config->single_item) ? 'product_page_main_image' : 'new_products_content_widget_grid';
                        ?>
                        <div class="product-item-info">
                        <a class="product-item-photo" href="<?php echo $_product->getProductUrl();?>" title="<?php echo $_productNameStripped; ?>">
                            <?php if ($config->enable_lazyload):?>
                                <?php $productImageBlock = $block->getImage($_product, $imageId, []); ?>
                                <img class="lazyOwl" <?php echo $productImageBlock->getCustomAttributes(); ?>
                                    data-src="<?php echo $productImageBlock->getImageUrl() ?>"
                                    alt="<?php echo $productImageBlock->stripTags($productImageBlock->getLabel(), null, true) ?>" />
                            <?php else: ?>
                                <?php echo $block->getImage($_product, $imageId, [])->toHtml(); ?>
                            <?php endif;?>
                        </a>
                        <div class="product-item-details">
                            <!-- product name-->
                            <?php if ($config->show_name): ?>
                            <strong class="product-item-name">
                                <a class="product-item-link" title="<?php echo $_productNameStripped?>" href="<?php echo $_product->getProductUrl();?>">
                                    <?php echo $block->escapeHtml($_product->getName()) ?>
                                </a>
                            </strong>
                            <?php endif; ?>

                            <!-- product short description-->
                            <?php if ($config->show_desc): ?>
                                <div class="product-description">
                                    <?php echo $blockHelper->subStrWords($block->stripTags($_product->getShortDescription()), $config->desc_length) ?>
                                </div>
                                <?php if ($config->show_readmore): ?>
                                <div class="product-readmore">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                       class="action more"><?php echo __('Read More') ?>
                                    </a>
                                </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <!-- product price-->
                            <?php if ($config->show_price): ?>
                                <?php echo $block->getProductPrice($_product) ?>
                            <?php endif; ?>

                            <!-- product review-->
                            <?php if ($config->show_review): ?>
                                <?php echo $block->getReviewsSummaryHtml($_product, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW, true); ?>
                            <?php endif; ?>

                            <!-- product links -->
                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                    <button class="action tocart primary"
                                                            data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postParams = $postDataHelper->getPostData(
                                                                $block->getAddToCartUrl($_product),
                                                                ['product' => $_product->getEntityId()]
                                                        );
                                                        $postParams = json_decode($postParams);
                                                        $uencName = \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED;
                                                    ?>
                                                    <form data-role="tocart-form"
                                                          action="<?= /* @NoEscape */ $postParams->action ?>" method="post"
                                                          data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" >
                                                        <input type="hidden" name="product" value="<?= $postParams->data->product ?>" />
                                                        <input type="hidden" name="<?= $uencName ?>" value="<?= $postParams->data->$uencName ?>" />
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit" title="<?= $block->escapeHtml(__('Add to Cart')) ?>" class="action tocart primary">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php endif; ?>
                                                <div class="stock available">
                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                </div>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   title="<?php echo __('Add to Wish List') ?>">
                                                    <span><?php echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?php echo $compareHelper->getPostDataParams($_product);?>'
                                                   title="<?php echo __('Add to Compare') ?>">
                                                    <span><?php echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endif; ?>

                <?php echo ($iterator == count($items)+1) ? '</div>' : '' ?>
                <?php endforeach; ?>
            </div>

            <!-- Thumbnail items-->
            <?php if ($config->single_item AND $config->show_thumbnail): ?>
            <div class="owl-carousel thumb-items">
                <?php foreach($items as $_product): ?>
                    <?php
                    //Load product data model for bestsellers products case only
                    if ($config->content_type == 'bestseller_products') {
                        $productData = $_product->getData();
                        $productId = isset($productData['product_id']) ? $productData['product_id'] : null;
                        $_product = $block->loadProductById($productId);
                    }
                    ?>
                    <?php if ($_product): ?>
                        <div class="item">
                            <?php $productImageBlock = $block->getImage($_product, 'side_column_widget_product_thumbnail', []); //side_column_widget_product_thumbnail, product_comparison_list ?>
                            <?php if ($config->enable_lazyload):?>
                                <img class="lazyOwl" <?php echo $productImageBlock->getCustomAttributes(); ?>
                                    data-src="<?php echo $productImageBlock->getImageUrl() ?>"
                                    alt="<?php echo $productImageBlock->stripTags($productImageBlock->getLabel(), null, true) ?>" />
                            <?php else: ?>
                                <img <?php echo $productImageBlock->getCustomAttributes(); ?>
                                    src="<?php echo $productImageBlock->getImageUrl() ?>"
                                    alt="<?php echo $productImageBlock->stripTags($productImageBlock->getLabel(), null, true) ?>" />
                            <?php endif;?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <?php endif; ?>
            <!--// Thumbnail items-->
        </div>
    </div>
    <!--// Slider content-->
    <?php else: ?>
        <div class="no-items"><?php echo __("There aren't items yet."); ?></div>
    <?php endif; ?>
</div>


