<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php 
/**
 * Get configuration values from UbThemeHelper
*/

/** @var \Ubertheme\UbThemeHelper\Helper\Data  $ubHelper */
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');
$toggleTab = "";
$toggleTab = (bool) $ubHelper->getParam('category_view/general/shop_by_toggle');

?>
<?php if ($block->canShowBlock()): ?>
            <div class="block filter">
                <div class="block-title filter-title">
                    <strong><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
                </div>

                <div class="block-content filter-content">
                    <?php echo $block->getChildHtml('state') ?>

                    <?php if ($block->getLayer()->getState()->getFilters()): ?>
                        <div class="block-actions filter-actions">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                        </div>
                    <?php endif; ?>
                    <?php $wrapOptions = false; ?>
                    <?php foreach ($block->getFilters() as $filter): ?>
                        <?php if (!$wrapOptions): ?>
                            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                            <div class="filter-options" id="narrow-by-list">
                        <?php $wrapOptions = true; endif; ?>
                            <?php if ($filter->getItemsCount()): ?>
                                <div class="filter-item">
                                    <h3 role="heading" aria-level="3" class="filter-options-title <?php if($toggleTab): ?>toggle-avaiable<?php endif; ?>"><?php echo $block->escapeHtml(__($filter->getName())) ?></h3>
                                    <div class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                                </div>
                            <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($wrapOptions): ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
<?php if($toggleTab): ?>
    <script type="text/javascript">    
    require([
        'jquery',
        'domReady!'        
        ],function($){
            $('.filter').addClass('tab-toggle');
            $('.filter-options .filter-options-title').click(function(){
                $(this).toggleClass('close');
                $(this).next().slideToggle();
            });
            $('.filter-options .filter-options-content').each(function(i){
                if(i==0) {            
                    $(this).prev().addClass('close');
                    $(this).css({'display':'block'});
                }else {
                    $(this).css({'display':'none'});
                }
            })
        });
    </script>
    <?php endif; ?>
<?php endif; ?>
