<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
/** @var \Ubertheme\UbThemeHelper\Helper\Data  $ubHelper */
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');

//Check and build custom CSS classes
$customClasses = [];
if (!(bool) $ubHelper->getParam('category_view/general/add_to_cart')) {
    $customClasses[] = 'hide-add-to-cart';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_compare')) {
    $customClasses[] = 'hide-add-to-compare';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_wishlist')) {
    $customClasses[] = 'hide-add-to-wishlist';
}
if (!(bool) $ubHelper->getParam('category_view/general/rating')) {
    $customClasses[] = 'hide-rating';
}
if (!(bool) $ubHelper->getParam('category_view/general/price')) {
    $customClasses[] = 'hide-price';
}
if (!(bool) $ubHelper->getParam('category_view/general/show_author')) {
    $customClasses[] = 'hide-author';
}
if (!(bool) $ubHelper->getParam('category_view/general/swatches')) {
    $customClasses[] = 'hide-swatches';
}
$customClasses = implode(' ', $customClasses);


if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    //$image = 'category_page_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
            <a href="books.html" title="<?php /* @escapeNotVerified */ echo $title; ?>"><?php /* @escapeNotVerified */ echo __('See more'); ?></a>
        </div>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type.' '.$customClasses ; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <div class="item-photo">
                                <?php
                                    $ubLabel = $ubHelper->getProductOptionTextByAttribute($_item, 'ub_label');
                                    $ubAuthor = $ubHelper->getProductOptionTextByAttribute($_item, 'ub_author');
                                ?>
                                <div class="ub-icon-label label-<?php echo strtolower(str_replace(' ', '', $ubLabel));?>"><?php echo $ubLabel; ?></div>
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                <button class="action tocart primary"
                                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php else: ?>
                                                <?php
                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                ?>
                                                <button class="action tocart primary"
                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In Stock') ?></i></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of Stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="product-item-details">
                                <h5 class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h5>
                                <div class="ub-author"><?= $ubAuthor; ?></div>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
                                <?= $block->getProductPriceHtml($_item, $type); ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>