<?php
/**
 * Webkul Software.
 *
 *
 * @category  Webkul
 * @package   Webkul_DeliveryBoy
 * @author    Webkul <support@webkul.com>
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html ASL Licence
 * @link      https://store.webkul.com/license.html
 */
?>
<div  data-role="global-messages-wrapper"
     data-bind='scope:"global-messages-wrapper", mageInit:{
       "Magento_Ui/js/core/app": {
                "components" : {
                    "global-messages-wrapper": {
                        "component" : "uiComponent",
                        "config": {
                            "template": "Webkul_DeliveryBoy/messages-wrapper"
                        },
                        "children": {
                            "messages": {
                                "component": "Webkul_DeliveryBoy/js/view/global-messages",
                                "displayArea": "messages",
                                "config": {
                                    "template": "Webkul_DeliveryBoy/global-messages",
                                    "selector": "[data-role=deliveryboy-global-messages]"
                                }
                            }
                        }
                    }
               }
          }   
     }'>
     <!-- ko template: getTemplate() --><!-- /ko -->
</div>
