<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="has-toggle  quick-search"  data-ui-id="quick-search" id="quick-search">
    <div class="search-product">
        <div class="btn-toggle">
            <span class="fa fa-search"></span>
            <strong><?php echo __('Search'); ?></strong>
        </div>
        <!-- <div class="box">
            <select>
                <option>All Categories</option>
                <option>opt2</option>
                <option>opt3</option>
            <select>
        </div> -->
        <div class="inner-toggle">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </label>
                        <div class="control">
                            <input id="search"
                            data-mage-init='{"quickSearch":{
                            "formSelector":"#search_mini_form",
                            "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                            "destinationSelector":"#search_autocomplete"}
                            }'
                            type="text"
                            name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                            value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                            placeholder="<?php /* @escapeNotVerified */ echo __('Enter Book Site jsbn,sku,publisher any keyboard'); ?>"
                            class="input-text"
                            maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                            role="combobox"
                            aria-haspopup="false"
                            aria-autocomplete="both"
                            autocomplete="off"/>
                            <div id="search_autocomplete" class="search-autocomplete"></div>
                                <?php echo $block->getChildHtml() ?>
                        </div>
                </div>
                <div class="actions">
                    <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                        <span class="fa fa-search"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>