<?php
$helper = $this->helper('Magecomp\Cancelorder\Helper\Data');
?>
<div class="block block-dashboard-orders">
    <?php $_orders = $block->getOrders(); ?>
    <div class="block-title order">
        <strong><?php /* @escapeNotVerified */ echo __('Recent Orders') ?></strong>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <a class="action view" href="<?php /* @escapeNotVerified */ echo $block->getUrl('sales/order/history') ?>">
                <span><?php /* @escapeNotVerified */ echo __('View All') ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
        <?php echo $block->getChildHtml() ?>
        <?php if (sizeof($_orders->getItems()) > 0): ?>
            <div class="table-wrapper orders-recent">
                <table class="data table table-order-items recent" id="my-orders-table">
                    <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Recent Orders') ?></caption>
                    <thead>
                        <tr>
                            <th scope="col" class="col id"><?php /* @escapeNotVerified */ echo __('Order #') ?></th>
                            <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                            <th scope="col" class="col total"><?php /* @escapeNotVerified */ echo __('Order Total') ?></th>
                            <th scope="col" class="col status"><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                            <th scope="col" class="col actions"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_orders as $_order): ?>
                            <tr>
                                <td data-th="<?php echo $block->escapeHtml(__('Order #')) ?>" class="col id"><?php /* @escapeNotVerified */ echo $_order->getRealOrderId() ?></td>
                                <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date"><?php /* @escapeNotVerified */ echo $block->formatDate($_order->getCreatedAt()) ?></td>
                                <td data-th="<?php echo $block->escapeHtml(__('Order Total')) ?>" class="col total"><?php /* @escapeNotVerified */ echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                                <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="col status"><?php /* @escapeNotVerified */ echo $_order->getStatusLabel() ?></td>
                                <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order) ?>" class="action view">
                                        <span><?php /* @escapeNotVerified */ echo __('View Order') ?></span>
                                    </a>
                                    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                            ->getPostData($block->getReorderUrl($_order))
                                        ?>' class="action order">
                                            <span><?= /* @escapeNotVerified */ __('Re-order') ?></span>
                                        </a>
                                    <?php endif ?>

                                    <?php if ($helper->isCancelOrderAllowed()): ?>
                                        <?php if($helper->OrderStatusCheck($_order->getStatus())) : ?>
                                            <?php if ($helper->isCommentEnabled()):?>
                                                <a href="#content-div-cancelorder-<?php echo $_order->getId(); ?>" class="action view border-none fancybox">
                                                    <span><?php echo __($helper->getCancelOrderButtonText()); ?></span>
                                                </a>
                                                <div style="display: none">
                                                    <div id="content-div-cancelorder-<?php echo $_order->getId(); ?>">
                                                    <div id="info-testy-create" style="padding: 4px;">
                                                            <form class="form contact"
                                                                  action="<?php echo $helper->getCancelOrderUrl($_order); ?>"
                                                                  id="commentForm"
                                                                  method="post"
                                                                  data-hasrequired="<?php echo __('* Required Fields') ?>"
                                                                  data-mage-init='{"validation":{}}'>
                                                                  <fieldset class="fieldset">
                                                                    <legend class="legend"><span style="font-weight: 400;"><?php echo __($helper->getPopupFormHeaderText()); ?></span></legend><br />
                                                                    <?php if (!empty($helper->getCancelReasons())): ?>
                                                                        <div class="field name required" style="margin-bottom: 10px;">
                                                                            <label class="label" for="comment"><span><?php echo __('Cancel Reasons') ?></span></label>
                                                                            <div class="control">
                                                                                <select name="cancel_reasons">
                                                                                    <?php echo $helper->getCancelReasons();?>
                                                                                    <option><?php echo __("Others")?></option>
                                                                                </select>
                                                                            </div>
                                                                        </div>
                                                                    <?php endif; ?>
                                                                    <div class="field name required" style="margin-bottom: 10px;">
                                                                        <label class="label" for="comment"><span><?php echo __('Comment') ?></span></label>
                                                                        <div class="control">
                                                                            <textarea name="comment" id="comment" title="<?php echo __('Comment') ?>" class="input-text" cols="45" rows="6" data-validate="{required:true}"></textarea>
                                                                        </div>
                                                                    </div>
                                                                    <p><?php echo $helper->getPopupFormNote(); ?></p>
                                                                    <div class="actions-toolbar">
                                                                        <div class="primary">
                                                                            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                                                                                <span><?php echo __('Submit') ?></span>
                                                                            </button>
                                                                            <button type="reset" class="button" value="<?php echo __('Reset') ?>"><span><span><?php echo __('Reset') ?></span></span></button>
                                                                        </div>
                                                                    </div>
                                                                  </fieldset>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            <?php else: ?>
                                                <a href="<?php echo $helper->getCancelOrderUrl($_order) ?>" class="action view">
                                                    <span><?php echo __($helper->getCancelOrderButtonText()); ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('You have placed no orders.'); ?></span></div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'cpfancybox'], function () {
        jQuery(document).ready(function () {
            jQuery(".fancybox").fancybox();
        });
    });
</script>
