<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */ ?>

<?php $parentItem = $block->getItem() ?>

<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $block->getChildren($parentItem) ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $helperData = $objectManager->get('\Retailinsights\Backorders\Helper\Data');
 ?>

<?php if ($block->getItemOptions() || $parentItem->getDescription() || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($_item->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if(!empty($attributes['option_id'])): ?>
			<?php if ($_prevOptionId != $attributes['option_id']): ?>
				<tr class="bundle-option-label">
					<td colspan="2">
						<strong><em><?= /* @escapeNotVerified */  $attributes['option_label'] ?></em></strong>
					</td>
				</tr>
				<?php $_prevOptionId = $attributes['option_id'] ?>
			<?php endif; ?>
		<?php endif; ?>
    <?php endif; ?>
    <?php if (!$_item->getParentItem()): ?>
        <tr class="bundle-item bundle-parent">
            <td class="item-info">
                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
            </td>
    <?php else: ?>
        <tr class="bundle-item bundle-option-value">
            <td class="item-info">
                <p><?= $block->getValueHtml($_item) ?></p>
                <?php if($helperData->isBackordred($_item)): ?>
             <div style="color: red; font-size: 10px"><?php echo $helperData->getBackOrderMessage('email_text'); ?></div> 
            <?php endif; ?>
            </td>
    <?php endif; ?>
            <td class="item-qty">
                <?php if (($block->isShipmentSeparately() && $_item->getParentItem()) || (!$block->isShipmentSeparately() && !$_item->getParentItem())): ?>
                    <?php if (isset($shipItems[$_item->getId()])): ?>
                        <?= /* @escapeNotVerified */  $shipItems[$_item->getId()]->getQty() * 1 ?>
                    <?php elseif ($_item->getIsVirtual()): ?>
                        <?= /* @escapeNotVerified */  __('N/A') ?>
                    <?php else: ?>
                        0
                    <?php endif; ?>
                <?php else: ?>
                    &nbsp;
                <?php endif; ?>
            </td>
        </tr>

<?php endforeach; ?>

<?php if ($_showlastRow): ?>
    <tr>
        <td colspan="2" class="item-extra">
            <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                            <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                <?php endforeach; ?>
            </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
    </tr>
<?php endif; ?>
