<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="has-toggle  quick-search"  data-ui-id="quick-search" id="quick-search">
    <div class="btn-toggle">
        <span class="fa fa-search"></span>
        <strong><?php echo __('Search'); ?></strong>
    </div>
    <!-- <div class="box">
        <select>
            <option>All Categories</option>
            <option>opt2</option>
            <option>opt3</option>
        <select>
    </div> -->
    <div class="inner-toggle">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                    <div class="control">
                        <input id="search"
                        data-mage-init='{"quickSearch":{
                        "formSelector":"#search_mini_form",
                        "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                        "destinationSelector":"#search_autocomplete"}
                        }'
                        type="text"
                        name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                        value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                        placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
                        class="input-text"
                        maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                        role="combobox"
                        aria-haspopup="false"
                        aria-autocomplete="both"
                        autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                            <?php echo $block->getChildHtml() ?>
                    </div>
            </div>
            <div class="actions">
                <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="4 5 28.8 28.8" style="width: 28px;height: 36px;"><path d="M26 16A11 11 0 0 0 15 5 11 11 0 0 0 4 16a11 11 0 0 0 11 11c2.6 0 5.1-.9 7-2.5l9.3 9.3 1.5-1.5-9.3-9.3c1.6-1.9 2.5-4.3 2.5-7zm-11 8.9c-4.9 0-8.9-4-8.9-8.9s4-8.9 8.9-8.9 8.9 4 8.9 8.9-4 8.9-8.9 8.9z"></path></svg>
                </button>
            </div>
        </form>
    </div>
</div>