<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->isEnabledViewSwitcher()): ?>
<div class="modes">
    <?php $_modes = $block->getModes(); ?>
    <?php if ($_modes && count($_modes) > 1): ?>
    <strong class="modes-label" id="modes-label"><?php /* @escapeNotVerified */ echo __('View as') ?></strong>
    <?php foreach ($block->getModes() as $_code => $_label): ?>
        <?php if ($block->isModeActive($_code)): ?>
            <?php if ($block->isModeActive($_code) == "grid"): ?>
              <strong title="<?php /* @escapeNotVerified */ echo $_label ?>"
                  class="modes-mode active mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                  data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                  <span><i class="fa fa-th-large"></i></span>
              </strong>  
            <?php else: ?>
              <strong title="<?php /* @escapeNotVerified */ echo $_label ?>"
                  class="modes-mode active mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                  data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                  <span><i class="fa fa-th-list"></i></span>
              </strong>
            <?php endif; ?>  
        <?php else: ?>
            <?php if ($block->isModeActive($_code) == "grid"): ?>
              <a class="modes-mode mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                 title="<?php /* @escapeNotVerified */ echo $_label ?>"
                 href="#"
                 data-role="mode-switcher"
                 data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                 id="mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                 aria-labelledby="modes-label mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                  <span><i class="fa fa-th-large"></i></span>
              </a>
            <?php else: ?>
              <a class="modes-mode mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                 title="<?php /* @escapeNotVerified */ echo $_label ?>"
                 href="#"
                 data-role="mode-switcher"
                 data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                 id="mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                 aria-labelledby="modes-label mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                  <span><i class="fa fa-th-list"></i></span>
              </a>
            <?php endif; ?>

            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php endif; ?>
