<div class="sitemap container">
    <div class="row">
        <div class="col-md-3">
            <h4 class="support-heading">Policy</h4>
            <ul class="support-list">
                <li class="product-item"><a href="#" class="footer-link">Terms and Conditions</a></li>
                <li class="product-item"><a href="#" class="footer-link">Cancellation & Return Policy</a></li>
                <li class="product-item"><a href="#" class="footer-link">Shipping Policy</a></li>
                <li class="product-item"><a href="#" class="footer-link">Privacy Policy</a></li>
                <li class="product-item"><a href="#" class="footer-link">Disclaimer</a></li>
                <li class="product-item"><a href="#" class="footer-link">FAQs</a></li>
            </ul>
        </div>
    
    
        <div class="col-md-3">
            <h3 class="">Contact Us</h3>
            <div class="mt-4">Toll-Free: 1800123333999</div>
            <div>help@centralbooksonline.com</div>
            <h5 class="mt-4">Our office Timing:</h5>
            <div>Mon-Sat: 10AM - 6:30PM</div>
        </div>
    </div>
    <div class="d-flex justify-content-around">
      <div>
        <h4 class="mt-4 font-weight-bold">Safe and Secure</h4>
        <div class="payment">
          <img src="<?php echo $this->getViewFileUrl('images/footer/payment_type.png'); ?>" alt="Payment" itemprop="image">
        </div>
      </div>
      <div>
        <h5 class="mt-4 font-weight-bold">Follow Us:</h5>
        <ul class="social-icon list-inline">
            <li class="social-item list-inline-item"><a href="#" target="_blank"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
            <li class="social-item list-inline-item"><a href="#" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li class="social-item list-inline-item"><a href="#" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
            <li class="social-item list-inline-item"><a href="#" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li class="social-item list-inline-item"><a href="#" target="_blank"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
        </ul>
      </div>
    </div>
</div>