<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/* @var $block \Magento\Framework\View\Element\Template */
$blockObj= $block->getLayout()->createBlock('Retailinsights\Registers\Block\Index\Header');
?>
<div class="header_logo_hide">
    <a href="<?php echo $blockObj->getCustUrl().'schools'; ?>">
        <img src="<?php echo $blockObj->getCustUrl(); ?>pub/media/ubertheme/school_zone/logo-centralbooks.png">
      </a>webId
</div>
