<?php

/**

 * Copyright © 2015 Magento. All rights reserved.

 * See COPYING.txt for license details.

 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');


/** @var $block \Magento\Framework\View\Element\Template */

$blockObj= $block->getLayout()->createBlock('Retailinsights\Registers\Block\Index\Header');

?>

<div class="has-toggle quick-access myaccount
<?php if(!$customerSession->isLoggedIn()){
              echo "profile_modal_hide";
            }else{ 
              
              echo "profile_modal";
            } 
        ?>"
		data-ui-id="quick-access" id="quick-access">

	<div class="btn-toggle link_container_acc">

		<!-- <img class="link_image" src="<?php // echo $blockObj->getCustUrl(); ?>pub/media/ubertheme/home/top.jpg"> -->
		<span class="fa fa-user"></span>

		<span class=""></span><strong><?php echo __('Profile') ?></strong>

	</div>

	<div class="inner-toggle">

		<div class="shop-access">

			<ul class="links">
				<?php echo $block->getChildHtml('', false); ?>
			</ul>

		</div>

	</div>

</div>

