<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <div class="content">
            <h2 class="color-blue"><?php /* @escapeNotVerified */ echo __('New Customers') ?></h2>
            <p><?php /* @escapeNotVerified */ echo __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?></p>
            <p class="auth-link">New User ? Click Here to <span class="register color-blue">Register</span></p>
        </div>
    </div>
</div>
<?php endif; ?>
