<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
/** @var \Ubertheme\UbThemeHelper\Helper\Data  $ubHelper */
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');
// Position for actions regarding image size changing in vde if needed
$pos = $block->getPositioned();
//Check and build custom CSS classes
$customClasses = [];
if (!(bool) $ubHelper->getParam('category_view/general/add_to_cart')) {
    $customClasses[] = 'hide-add-to-cart';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_compare')) {
    $customClasses[] = 'hide-add-to-compare';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_wishlist')) {
    $customClasses[] = 'hide-add-to-wishlist';
}
if (!(bool) $ubHelper->getParam('category_view/general/rating')) {
    $customClasses[] = 'hide-rating';
}
if (!(bool) $ubHelper->getParam('category_view/general/price')) {
    $customClasses[] = 'hide-price';
}
if (!(bool) $ubHelper->getParam('category_view/general/show_author')) {
    $customClasses[] = 'hide-author';
}
if (!(bool) $ubHelper->getParam('category_view/general/swatches')) {
    $customClasses[] = 'hide-swatches';
}
$customClasses = implode(' ', $customClasses);

$enabledHoverImage = (bool) $ubHelper->getParam('category_view/general/enable_alternative_product');

?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $imageId = 'category_page_grid';
    $hoverImageId = 'category_page_grid_hover';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type.' '.$customClasses ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <?php
                            $ubLabel = $ubHelper->getProductOptionTextByAttribute($_item, 'ub_label');
                            $ubAuthor = $ubHelper->getProductOptionTextByAttribute($_item, 'ub_author');
                            //get product image
                            $productImage = $block->getImage($_item, $imageId);

                            //check hover image
                            $hasHoverImage = false;
                            if ($enabledHoverImage) {
                                $productImageHover = $block->getImage($_item, $hoverImageId);
                                if (!preg_match('/(product\/placeholder)/i', $productImageHover->getImageUrl())) {
                                    $hasHoverImage = true;
                                }
                            }

                            
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            $paddingStyleList = "";
                            if ($block->getMode() == 'list') {
                                $paddingStyleList = "padding-left: ".$productImage->getWidth()."px;"; 
                            }

                        ?>
                        <div class="product-item-info">
                            <div class="item-photo">
                                <a href="<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <span class="ub-icon-label label-<?php echo strtolower(str_replace(' ', '', $ubLabel));?>"><?php echo $ubLabel; ?></span>
                                    <span class="main-image"> <?= $productImage->toHtml(); ?> </span>
                                    <?php if ($hasHoverImage): ?>
                                        <span class="hover-image" style="display: none;"> <?= $productImageHover->toHtml(); ?> </span>
                                    <?php endif; ?>
                                </a>
                                <div class="product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <div class="ub-author"><?= $ubAuthor; ?></div>
                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                <?php endif; ?>
                                <?= $block->getProductPriceHtml($_item, $type) ?>
                                <?= $block->getProductDetailsHtml($_item) ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
