<?php
/**
 * @package     Plumrocket_RMA
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */

/** @var \Plumrocket\RMA\Block\Adminhtml\Returns\Messages $block */
?>

<?php $_entity = $block->getEntity() ?>
<?php $_order = $block->getOrder() ?>

<div class="admin__page-section-item-title">
    <span class="title"><?= $block->escapeHtml(__('Messages')) ?></span>
    <?php if ($block->showMarkAsRead()) : ?>
        <div class="actions">
            <a id="mark_as_read" href="#">
                <?= $block->escapeHtml(__('Mark all as read')) ?>
            </a>
        </div>
    <?php endif; ?>
</div>

<div id="returns_comments_block" class="edit-order-comments">
    <div class="order-history-block" id="returns_comments_form">

        <div class="admin__field">
            <label for="returns_comment_template" class="admin__field-label">
                <?= $block->escapeHtml(__('Use Response Template')) ?>
            </label>
            <div class="admin__field-control">
                <select name="comment_template" id="returns_comment_template" class="admin__control-select">
                    <option value="0"><?= $block->escapeHtml(__('Choose Template')) ?></option>
                    <?php foreach ($block->getResponseTemplates() as $_item): ?>
                        <option value="<?= $block->escapeHtml($_item->getId()) ?>"><?= $this->escapeHtml($_item->getTitle()) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="admin__field">
            <label for="returns_comment" class="admin__field-label">
                <?= $block->escapeHtml(__('Comment (optional)')) ?>
            </label>
            <div class="admin__field-control">
                <?= $block->getEditor()->getElementHtml() ?>
            </div>
        </div>

        <div class="admin__field">
            <div class="contents-uploader">
                <?= $this->getChildHtml('rma.returns.messages.uploader') ?>
            </div>

            <div class="order-history-comments-options">
                <div class="admin__field admin__field-option">
                    <?php $element = $block->getCheckboxOfInternal() ?>
                    <?= $element->getElementHtml() ?>
                    <?= $element->getLabelHtml() ?>
                </div>
                <div class="admin__field admin__field-option">
                    <?php $element = $block->getCheckboxOfEmail() ?>
                    <input type="hidden" name="<?= $element->getName() ?>" value="0" />
                    <?= $element->getElementHtml() ?>
                    <?= $element->getLabelHtml() ?>
                </div>
            </div>
        </div>
    </div>

    <ul class="note-list returns-comments-list">
    <?php foreach ($block->getMessages() as $_item): ?>
        <li class="comment-item sender-<?php echo $block->escapeHtml($_item->getType()) ?>">
            <span class="note-list-customer">
                <span class="note-list-customer-notified">
                    <?= $block->escapeHtml($_item->getName()) ?>
                    <?php if ($block->isFromYou($_item)): ?>
                        <?= $block->escapeHtml(__('(You)')) ?>
                    <?php endif; ?>

                    <?php if ($_item->getIsInternal()): ?>
                        <span class="comment-internal">(Internal)</span>
                    <?php endif; ?>
                </span>
            </span>
            <span class="note-list-date"><?php /* @noEscape */ echo $block->formatDate($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
            <span class="note-list-time"><?php /* @noEscape */ echo $block->formatTime($_item->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?></span>
            <?php if ($_item->getText()): ?>
                <div class="note-list-comment">
                    <?= $_item->getContentHtml() ?>
                </div>
            <?php endif; ?>

            <?php if ($files = $_item->getPreparedFiles()): ?>
                <div class="comment-files">
                    <span class="prrma-att-file"></span>
                    <?php foreach ($files as $file): ?>
                        <a href="<?php echo $block->escapeHtml($block->getFileUrl($file['filename'])) ?>" target="_blank">
                            <?= $block->escapeHtml($file['name']) ?>
                        </a><?php echo next($files) ? ', ' : '' ?>
                    <?php endforeach ?>
                </div>
            <?php endif ?>
        </li>
    <?php endforeach; ?>
    </ul>

    <script type="text/javascript">
        window.markAsReadUrl = '<?php echo $this->escapeJsQuote($block->getMarkAsReadUrl()); ?>';
        window.responseTemplateUrl = '<?php echo $this->escapeJsQuote($block->getLoadTemplateUrl()); ?>';
    </script>
</div>
