<?php
/**
 * @package     Plumrocket_RMA
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (https://plumrocket.com)
 * @license     https://plumrocket.com/license   End-user License Agreement
 */
?>

<div class="admin__page-section-item-title">
    <span class="title"><?php /* @escapeNotVerified */ echo __('Upload Shipping Label') ?></span>
</div>

<div id="returns_shipping_label_block" class="admin__page-section-item-content">
    <div class="admin__field">
        <div class="contents-uploader">
            <?php echo $this->getChildHtml('rma.returns.shipping_label.uploader') ?>
        </div>
    </div>

    <?php if ($block->hasShippingLabel()): ?>
        <div class="shipping-label">
            <?php echo __('Shipping label attached') ?>
            <a class="button action print-shipping" href="<?php echo $block->getShippingLabelUrl() ?>" target="_blank">
                <img src="<?php echo $block->getShippingLabelUrl() ?>" alt="" />
                <span><?php echo __('Print Shipping Label') ?></span>
            </a>

            <?php $element = $block->getCheckboxOfDelete() ?>
            <?php echo $element->getElementHtml() ?>
            <?php echo $element->getLabelHtml() ?>
        </div>
    <?php endif ?>

</div>
