<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <div class="content">
                <h2 class="color-blue"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></h2>
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your mobile/email.') ?></div>
                <p class="auth-link">Existing User ? Click Here to <span class="login color-blue">Login</span></p>
            </div>
        </form>
    </div>
</div>
