<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
$mediaUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$finalmediaPath = $mediaUrl.'orderexport.csv';
?>

<div class="content-header" style="border-bottom:none;">
	<div class="entry-edit">
	    <div class="fieldset" id="base_fieldset">
				<div class="hor-scroll">
							<tr>
								<td class="label">
								<label><h4>Export Order Link</h4></label>  <?php echo $this->getUrl("orderexport/exportorder/export") ; ?>
								</td>
							</tr>
							
							<tr>
								<td></br></br></td>
								<td> 
									<span>
										<span>
											<?php echo __('Order Download link') ?> 
										</span>
										<span><a href="<?php echo $finalmediaPath ; ?>">Download</a></span>
									</span>								
								</td>
							</tr>
				</div>
			</div>
	</div>
</div>

<style>
#exportorderform label {
    float: left;
    width: 10%;
}
</style>