<link href="<?php echo $block->getAssetUrl('Webkul_DeliveryBoy::css/deliveryboy.css'); ?>" type="text/css" rel="stylesheet" />
<?php
/**
 * Webkul Software.
 *
 *
 * @category  Webkul
 * @package   Webkul_DeliveryBoy
 * @author    Webkul <support@webkul.com>
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html ASL Licence
 * @link      https://store.webkul.com/license.html
 */
if ($block->canAddReview()):
    $deliveryboyOrderId = $block->getDeliveryboyOrderId();?>
    <div class="deliveryboy-review-wrapper" data-block="deliveryboy-review">
        <div id='deliveryboy-review_<?= /** @noEscape */ $deliveryboyOrderId; ?>'
            data-role="deliveryboy-review-loader"
            class="loading-mask" data-mage-init='{"Webkul_DeliveryBoy/js/view/review-loader": {}}'>
            <div class="loader">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                    alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                    style="position: absolute;">
            </div>
        </div>
        <div class="actions deliveryboy-review-action-wrapper">
            <button class="action add-review" data-trigger="deliveryboy-add-review">
                <span><?= $block->escapeHtml(__('Add Review')) ?></span>
            </button>
        </div>
        <div class="review-add block-deliveryboy-review"
             style="display: none;"
             data-mage-init='{"Webkul_DeliveryBoy/js/view/add-review": {
                 "deliveryboyOrderId": "<?= $block->escapeHtmlAttr($deliveryboyOrderId); ?>"
             }}'>
            <div class="block block-deliveryboy-add-review">
                <div data-role="modal-messages" class="modal-messages"
                     data-bind='scope:"messages-wrapper", mageInit: {
                        "Magento_Ui/js/core/app": {
                            "components" : {
                                "messages-wrapper": {
                                    "component" : "uiComponent",
                                    "config": {
                                        "template": "Webkul_DeliveryBoy/messages-wrapper"
                                    },
                                    "children": {
                                        "messages": {
                                            "component": "Webkul_DeliveryBoy/js/view/modal-messages",
                                            "displayArea": "messages"
                                        }
                                    }
                                }
                            }
                        }}'>
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <div class="block-content">
                    <form action="<?= $block->escapeUrl($block->getAddReviewAction()); ?>"
                        class="deliveryboy-review-form" method="post"
                        data-role="deliveryboy-review-form"
                        data-bind='mageInit: {
                            "Webkul_DeliveryBoy/js/validate-review": {},
                            "Webkul_DeliveryBoy/js/error-placement": {}
                        }'>
                        <?php $deliveryBoy = $block->getDeliveryBoy(); ?>
                        <input
                            type="hidden"
                            name="deliveryBoyId"
                            value="<?= $block->escapeHtmlAttr($deliveryBoy->getId()); ?>" />
                        <input
                            type="hidden"
                            name="rating"
                            id="ratingActiveStar"
                            value="" />
                        <input
                            type="hidden"
                            name="customerId"
                            value="<?= $block->escapeHtmlAttr($block->getCustomerId()); ?>" />
                        <fieldset class="fieldset deliveryboy-review-fieldset"
                            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                            <legend class="legend deliveryboy-review-legend">
                                <span><?= $block->escapeHtml(__("You're reviewing:")) ?></span>
                                <strong><?= $block->escapeHtml($block->getDeliveryboy()->getName()) ?></strong>
                            </legend><br />
                            <fieldset class="field required deliveryboy-review-field-ratings">
                                <legend class="label">
                                    <span><?= $block->escapeHtml(__('Your Rating')) ?></span>
                                </legend><br/>
                                <div class="control rating">
                                    <i class="rating__star far fa-star"></i>
                                    <i class="rating__star far fa-star"></i>
                                    <i class="rating__star far fa-star"></i>
                                    <i class="rating__star far fa-star"></i>
                                    <i class="rating__star far fa-star"></i>
                                </div>
                            </fieldset>
                            <div class="field required">
                                <label for='deliveryboy_title_field_<?= /** @noEscape */ $deliveryboyOrderId; ?>'
                                    class="label">
                                    <span><?= $block->escapeHtml(__('Title')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="title"
                                        id='deliveryboy_title_field_<?= /** @noEscape */ $deliveryboyOrderId; ?>'
                                        class="input-text" data-validate="{required:true}"
                                    />
                                </div>
                            </div>
                            <div class="field required">
                                <label for="deliveryboy_comment_field_<?= /** @noEscape */ $deliveryboyOrderId; ?>"
                                    class="label">
                                    <span><?= $block->escapeHtml(__('Comment')) ?></span>
                                </label>
                                <div class="control">
                                    <textarea name="comment"
                                        id="deliveryboy_comment_field_<?= /** @noEscape */ $deliveryboyOrderId; ?>"
                                        cols="5" rows="3"
                                        data-validate="{required:true}"></textarea>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<script>
    const ratingStars = [...document.getElementsByClassName("rating__star")];

    function executeRating(stars) {
        const starClassActive = "rating__star fas fa-star";
        const starClassInactive = "rating__star far fa-star";
        const starsLength = stars.length;
        let i;
        let count = 0;
        stars.map((star) => {
            star.onclick = () => {
                i = stars.indexOf(star);
                document.getElementById("ratingActiveStar").value = i + 1;
                if (star.className===starClassInactive) {
                    for (i; i >= 0; --i){
                        stars[i].className = starClassActive;
                    }

                } else {
                    for (i; i < starsLength; ++i){
                        stars[i].className = starClassInactive;
                    }
                }
            };      
        });
    }
    executeRating(ratingStars);
</script>