<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>

<?php
    /** @var  \Ubertheme\UbThemeHelper\Block\Adminhtml\Config\Form\Field\Tab\Items $block */
    $htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
    $colspan = $block->isAddAfter() ? 2 : 1;
    $dependingColumns = $block->getDependingColumns();
?>

<div class="design_theme_ua_regexp" id="grid<?= /* @escapeNotVerified */ $htmlId ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= /* @escapeNotVerified */ $block->getElement()->getId() ?>" data-mage-init='{"ubDraggableFields": {}}'>
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <?php if (!in_array($columnName, $dependingColumns)) : ?>
                        <th><?= /* @escapeNotVerified */ $column['label'] ?></th>
                    <?php endif; ?>
                <?php endforeach;?>
                <th class="col-actions" colspan="<?= /* @escapeNotVerified */ $colspan ?>"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="<?= (count($block->getColumns()) - 2) + $colspan ?>" class="col-actions-add">
                    <button id="addToEndBtn<?= /* @escapeNotVerified */ $htmlId ?>" class="action-add" title="<?= /* @escapeNotVerified */ __('Add') ?>" type="button">
                        <span><?= /* @escapeNotVerified */ $block->getAddButtonLabel() ?></span>
                    </button>
                    <?= $block->getHtmlResetButton(); ?>
                </td>
            </tr>
            </tfoot>
            <tbody id="addRow<?= /* @escapeNotVerified */ $htmlId ?>" data-role="row-container"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?= /* @escapeNotVerified */ $block->getElement()->getName() ?>[__empty]" value="" />

    <script>
        require([
            'mage/template',
            'prototype',
            'jquery',
            'jquery/ui',
            'jquery/validate',
            'mage/translate'
        ], function (mageTemplate) {
            // create row creator
            window.arrayRow<?= /* @escapeNotVerified */ $htmlId ?> = {

                // define row prototypeJS template
                template: mageTemplate(
                    '<tr id="<%- _id %>">'

                    + '<td class="col-draggable" >  <div data-role="draggable-handle" class="draggable-handle"\n title="<?= __('Sort this row') ?>"></div>'

                    + ' <input data-role="sort-control" type="hidden" name="is_default" value="" />'

                    <?php foreach ($block->getColumns() as $columnName => $column): ?>

                        <?php if (!in_array($columnName, $dependingColumns)) : ?>

                            + '<td <?php echo ($columnName == "type") ? "id = \"type-default<%- _id %>\"" : "" ?> class="col-attributes <?php echo ($columnName == 'type_default') ? "is-default" : "" ?>">'

                            + '<?= /* @escapeNotVerified */ $block->renderCellTemplate($columnName) ?>'

                            <?php if (isset($column['depending_columns']) && is_array($column['depending_columns'])): ?>
                                <?php foreach ($column['depending_columns'] as $columnName): ?>
                                + '<?= /* @escapeNotVerified */ $block->renderCellTemplate($columnName) ?>'
                                <?php endforeach; ?>
                            <?php endif; ?>

                        + '<\/td>'

                        <?php endif; ?>

                    <?php endforeach; ?>

                    <?php if ($block->isAddAfter()): ?>
                    + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span><?= /* @escapeNotVerified */ __('Add after') ?><\/span><\/button><\/td>'
                    <?php endif; ?>

                    + '<td class="col-actions"><button onclick="arrayRow<?= /* @escapeNotVerified */ $htmlId ?>.del(\'<%- _id %>\')" class="action-delete" id="delete<%- _id %>" type="button"><span><?= /* @escapeNotVerified */ __('Delete') ?><\/span><\/button><\/td>'

                    +'<\/tr>'
                ),
                add: function(rowData, insertAfterId) {
                    // generate default template data
                    var templateValues;

                    // Prepare template values
                    if (rowData) {
                        templateValues = rowData;
                    } else {
                        var d = new Date();
                        templateValues = {
                        <?php foreach ($block->getColumns() as $columnName => $column): ?>
                        <?= /* @escapeNotVerified */ $columnName ?>: '',
                            'option_extra_attrs': {},
                        <?php endforeach; ?>
                        _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                    };
                    }

                    // Insert new row after specified row or at the bottom
                    if (insertAfterId) {
                        Element.insert($(insertAfterId), {after: this.template(templateValues)});
                    } else {
                        Element.insert($('addRow<?= /* @escapeNotVerified */ $htmlId ?>'), {bottom: this.template(templateValues)});
                    }

                    // Fill controls with data
                    if (rowData) {
                        var rowInputElementNames = Object.keys(rowData.column_values);
                        var rowId = rowData._id;
                        var isDefault = rowData.type_default;
                        for (var i = 0; i < rowInputElementNames.length; i++) {
                            if ($(rowInputElementNames[i])) {
                                $(rowInputElementNames[i]).setValue(rowData.column_values[rowInputElementNames[i]]);
                                var id = $(rowInputElementNames[i]).id;
                                var type = rowData.type;
                                var status = rowData.status;

                                //Modify status field
                                if (id.includes('_status')) {
                                    if (!status) {
                                        $(rowId + '_status').writeAttribute('data-status','');
                                    }
                                    if ($('product_view_ub_custom_tab_tab_content_items_inherit').getValue()) {
                                        $(rowInputElementNames[i]).next().addClassName('disabled-status');
                                    }
                                }

                                //Check case tab is default magento
                                if (isDefault) {
                                    if(id.includes('_static_block') || id.includes('_attribute_code')){
                                        $(rowInputElementNames[i]).disabled = true;
                                    }
                                    if ($(rowId+'_type')) {
                                        $(rowId+'_type').remove();
                                        if (isDefault === 'product.info.description') {
                                            $('type-default'+rowId).insert('<p class="core-default"><?php echo __('System Description') ?></p>');
                                        } else if(isDefault === 'reviews.tab') {
                                            $('type-default'+rowId).insert('<p class="core-default"><?php echo __('System Review') ?></p>');
                                        }else{
                                            $('type-default'+rowId).insert('<p class="core-default"><?php echo __('System More Information') ?></p>');
                                        }
                                    }
                                    if ($('delete'+rowId)) {
                                        $('delete'+rowId).disabled = true;
                                    }
                                } else {
                                    //element is attribute
                                    if (id.includes('_attribute_code')) {
                                        if (type === 'static_block') {
                                            $(rowInputElementNames[i]).disabled = true;
                                        }
                                    }
                                    //element is static block
                                    if (id.includes('_static_block')) {
                                        $(rowInputElementNames[i]).disabled = false;
                                        if (type === 'attribute_code') {
                                            $(rowInputElementNames[i]).disabled = true;
                                        }
                                    }
                                }
                            }
                        }
                    }

                    // Add event for {addAfterBtn} button
                    <?php if ($block->isAddAfter()): ?>
                    Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
                    <?php endif; ?>

                    //trigger change on type field
                    jQuery('.ubcustom-tab-type').trigger('change');
                },
                del: function(rowId) {
                    $(rowId).remove();
                }
            }

            // bind add action to "Add" button in last row
            Event.observe('addToEndBtn<?= /* @escapeNotVerified */ $htmlId ?>', 'click', arrayRow<?= /* @escapeNotVerified */ $htmlId ?>.add.bind(arrayRow<?= /* @escapeNotVerified */ $htmlId ?>, false, false));

            // add existing rows
            <?php
                foreach ($block->getArrayRows() as $_rowId => $_row) {
                    /* @escapeNotVerified */ echo "arrayRow{$htmlId}.add(" . $_row->toJson() . ");\n";
                }
            ?>

            // Toggle the grid availability, if element is disabled (depending on scope)
            <?php if ($block->getElement()->getDisabled()):?>
                toggleValueElements({checked: true}, $('grid<?= /* @escapeNotVerified */ $htmlId ?>').parentNode);
            <?php endif;?>

            //Reset default value custom tab
            window.resetToDefaultTabs = function () {
                jQuery('#product_view_ub_custom_tab_tab_content_items tbody tr').each(function () {
                    jQuery(this).remove();
                })
                <?php
                foreach ($block->getArrayRowsDefault() as $_rowId => $_row) {
                    /* @escapeNotVerified */ echo "arrayRow{$htmlId}.add(" . $_row->toJson() . ");\n";
                }
                ?>
            }
        });
    </script>
</div>