<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');
?>

<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_wishhelper = $this->helper('Retailinsights\Registers\Helper\Data');

// Position for actions regarding image size changing in vde if needed
$pos = $block->getPositioned();

/**
 * Get configuration values from UbThemeHelper
*/

/** @var \Ubertheme\UbThemeHelper\Helper\Data  $ubHelper */
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');

//Check and build custom CSS classes
$customClasses = [];
if (!(bool) $ubHelper->getParam('category_view/general/add_to_cart')) {
    $customClasses[] = 'hide-add-to-cart';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_compare')) {
    $customClasses[] = 'hide-add-to-compare';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_wishlist')) {
    $customClasses[] = 'hide-add-to-wishlist';
}
if (!(bool) $ubHelper->getParam('category_view/general/rating')) {
    $customClasses[] = 'hide-rating';
}
if (!(bool) $ubHelper->getParam('category_view/general/price')) {
    $customClasses[] = 'hide-price';
}
if (!(bool) $ubHelper->getParam('category_view/general/show_author')) {
    $customClasses[] = 'hide-author';
}
if (!(bool) $ubHelper->getParam('category_view/general/swatches')) {
    $customClasses[] = 'hide-swatches';
}
$customClasses = implode(' ', $customClasses);

$enabledHoverImage = (bool) $ubHelper->getParam('category_view/general/enable_alternative_product');

$enabledInfiniteScroll = (bool) $ubHelper->getParam('element/main/infinite_scroll/infinite_scroll_general/enable');
$showToolbar = "";
if($enabledInfiniteScroll) {
    $showToolbar = 'style="display: none"';
}


if ($block->getMode() == 'grid') {
    $viewMode = 'grid';
    $imageId = 'category_page_grid';
    $hoverImageId = 'category_page_grid_hover';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    
    $viewMode = 'list';
    $imageId = 'category_page_list';
    $hoverImageId = 'category_page_list_hover';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    //Config for List Product from UB ThemeHelper
    $showDesc = $ubHelper->getParam('category_view/list/enable_description');
    $descLimit = $ubHelper->getParam('category_view/list/max_char');
}

   
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items <?= $customClasses;?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $isSameSchool = $this->helper('SchoolZone\Addschool\Helper\Data')->isProductFromSameSchool($_product->getId());?>
                <?php 
                   $qtyAvailable = $_product->isSaleable();
                ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $ubLabel = $ubHelper->getProductOptionTextByAttribute($_product, 'ub_label');
                    $ubAuthor = $ubHelper->getProductOptionTextByAttribute($_product, 'ub_author');

                    //get product image
                    $productImage = $block->getImage($_product, $imageId);

                    //check hover image
                    $hasHoverImage = false;
                    if ($enabledHoverImage) {
                        $productImageHover = $block->getImage($_product, $hoverImageId);
                        if (!preg_match('/(product\/placeholder)/i', $productImageHover->getImageUrl())) {
                            $hasHoverImage = true;
                        }
                    }

                    
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    $paddingStyleList = "";
                    if ($block->getMode() == 'list') {
                        $paddingStyleList = "padding-left: ".$productImage->getWidth()."px;"; 
                    }


                    ?>
                    <?php // Product Image ?>
                    <div class="item-photo">
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php if(!empty($ubLabel)) { ?>
                            <span class="ub-icon-label label-<?php echo strtolower(str_replace(' ', '', $ubLabel));?>"><?php echo $ubLabel; ?></span>
							<?php } ?>
                            <span class="main-image"> <?= $productImage->toHtml(); ?> </span>
                            <?php if ($hasHoverImage): ?>
                                <span class="hover-image" style="display: none;"> <?= $productImageHover->toHtml(); ?> </span>
                            <?php endif; ?>
                        </a>
                        
                        <?php if ($block->getMode() == 'grid'): ?>
                            <div class="product actions product-item-actions"<?= ($pos && strpos($pos, $viewMode . '-actions')) ? $position : '' ?>>
                                <div class="actions-primary"<?= ($pos && strpos($pos, $viewMode . '-primary')) ? $position : '' ?>>
                               
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post" data-productName="<?=$_product->getName()?>">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            
                                            <?php if($isSameSchool && ($qtyAvailable != 0)): ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary click_here_to_buy">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                            <?php endif; ?>
                                        </form>
                                        <?php if ($qtyAvailable != 0): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In Stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of Stock'); ?></span></div>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable() && ($qtyAvailable != 0)): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In Stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of Stock'); ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                     <?php
                             $wish_class = $_wishhelper->isWishlist($_product->getId());
                             ?>
                                <div data-role="add-to-links" class="actions-secondary <?= ($pos && strpos($pos, $viewMode . '-secondary')) ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                                </div>
                            </div>
                        <?php else: ?>
                            <div class="product actions product-item-actions"></div>
                        <?php endif;  ?>

                    </div>
                    <div class="product details product-item-details" style="<?= $paddingStyleList;?>">
                        <h5 class="product name product-item-name">
                            <a class="product-item-link catalog-productName" title="<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>"
                            href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                        </a>
                    </h5>
                    <?= $block->getProductDetailsHtml($_product); ?>
                    <div class="ub-author"><?= $ubAuthor; ?></div>
                    <?= $block->getReviewsSummaryHtml($_product, $templateType, true);  ?>
                        <?= $block->getProductPrice($_product); ?>
                        <?php if ($showDescription && $showDesc): ?>
                            <div class="product-item-inner">
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ 
                                        $_strShortDesc = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                                        echo substr($_strShortDesc, 0, $descLimit);
                                    ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if ($block->getMode() == 'list'): ?>
                            <div class="actions-primary">
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <?php if($isSameSchool && ($qtyAvailable != 0)): ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    </form>
                                    <?php if ($qtyAvailable != 0): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In Stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of Stock'); ?></span></div>
                                        <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In Stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of Stock'); ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <?php
                           $wish_class = $_wishhelper->isWishlist($_product->getId());
                             ?>
                            <div data-role="add-to-links" class="actions-secondary <?php echo $wish_class; ?>"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                <?php endif; ?>
                            </div>
                        <?php endif;  ?>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="toolbar-bottom" <?php echo $showToolbar;?>>
    <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php if ($enabledHoverImage): ?>
    <script>
        require([
            'jquery',
            'domReady!'
        ], function($){
            if($('.website_id').val() == 3){
                // $(".ub-quick-view-btn-container").css({"display": "none"});
                  // $(".ub-quick-view-btn-container").attr('style', 'display: none !important');
                  // $(".reviews-actions").attr('style', 'display: none');
                  // $(".price-final_price").attr('style', 'display: none');
                 
            }

            var transition = 'fast';
            $('.product-item-photo .main-image').mouseenter(function() {
                if ($(this).siblings('.hover-image').length) {
                    $(this).fadeOut(transition, function() {
                        $(this).siblings('.hover-image').fadeIn(transition);
                    });
                }
            });
            $('.product-item-photo .hover-image').mouseleave(function() {
                $(this).fadeOut(transition, function() {
                    $(this).siblings('.main-image').fadeIn(transition);
                });
            });


        });
    </script>
<?php endif; ?>
