<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Multi */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections(); ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <tr class="content-title"><td><h2><label class="label" for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>">
        <?= $block->escapeHtml($_option->getTitle()) ?>
    </label>*</h2></td><td></td><td></td><td></td></tr>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
            <input data-rprice = "<?php echo (int)$_selections[0]->getSelectionQty()*$_selections[0]->getFinalPrice(); ?>" type="hidden"
                   name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                   value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
        <?php else: ?>
            <tr><td><div class="noteMsg">Note: Press CTRL+Click to select multiple books here</div></td><td></td><td></td><td></td></tr>
            <tr><td> <select multiple="multiple"
                    size="5"
                    id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>"
                    name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][]"
                    data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][]"
                    class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?> multiselect product bundle option change-container-classname"
                    <?php if ($_option->getRequired()) echo 'data-validate={required:true}' ?>>
                <?php if(!$_option->getRequired()): ?>
                    <option value=""><?= /* @escapeNotVerified */ __('None') ?></option>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>

                    <option data-rprice = "<?php echo (int)$_selection->getSelectionQty()*$_selection->getFinalPrice(); ?>" value="<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"
                            <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                            <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>
                        <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection, true) ?>
                    </option>
                <?php endforeach; ?>
            </select></td><td></td><td></td><td></td></tr>
        <?php endif; ?>
    </div>
</div>
<style>
    .product-options-wrapper select {
        width: 100%;
    }
</style>
