<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer
 */
/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer */
?>

<?php $_item = $block->getItem() ?>
<?php $items = array_merge([$_item], $_item->getChildrenItems()); ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $helperData = $objectManager->get('\Retailinsights\Backorders\Helper\Data');
 ?>

<?php $_prevOptionId = '' ?>

<?php if($block->getOrderOptions() || $_item->getDescription() || $block->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_item->getParentItem()): ?>
	<?php if(!empty($attributes['option_id'])): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product"><div class="option-label"><?= /* @escapeNotVerified */ $attributes['option_label'] ?></div></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
        <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
		<?php endif; ?>
    <?php endif; ?>
    <tr<?= (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?>>

	<?php if (!$_item->getParentItem()): ?>
	<?php $parent_product_id = $_item->getProductId(); ?>
	<?php endif; ?>
	   <?php 
	    /*$productid = $_item->getProductId();
	    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$tableName = $resource->getTableName('catalog_product_bundle_selection');
		$sql = "Select * FROM " . $tableName ." where parent_product_id = " . $parent_product_id ." AND product_id = " . $productid ;
		$product_given_collection = $connection->fetchRow($sql);*/  
		?>
		
		<?php if (!$_item->getParentItem()): ?>
        <td class="col-product custom_class_mani">
            <div class="product-title" id="order_item_<?= /* @escapeNotVerified */ $_item->getId() ?>_title">
                <?= $block->escapeHtml($_item->getName()) ?>
            </div>
            <div class="product-sku-block">
                <span><?= /* @escapeNotVerified */ __('SKU') ?>:</span>
                <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($_item->getSku()))) ?>
            </div>
        </td>
        <?php else: ?>
        <td class="col-product">
            <div class="option-value"><?= $block->getValueHtml($_item) ?></div>
            <?php if($block->isBackorder($_item)): ?>
            <div style="color: red;"><?php echo $this->helper('\Retailinsights\Backorders\Helper\Data')->getBackOrderMessage('admin_text'); ?></div> 
            <?php endif; ?>
			    
			<?php

			$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

			/** @var \Magento\Variable\Model\Variable $variable */
			$variable = $objectManager->create(\Magento\Variable\Model\Variable::class)
				->loadByCode('given_option_switch_date');

			$configDate = trim((string)$variable->getPlainValue());
			if (!empty($configDate)) {
				$compareDate = strtotime($configDate . ' 23:59:59');
			} else {
				$compareDate = strtotime('2026-03-02 23:59:59');
			}

			$orderTimestamp = strtotime($_item->getOrder()->getCreatedAt());

			$givenOption = (int)$_item->getGivenOptions();
			$message     = $_item->getGivenOptionsMsg();

			if ($orderTimestamp > $compareDate) {

				if ($givenOption === 1 || $givenOption === 2) {
					echo '<div style="color:red;">' . $block->escapeHtml($message) . '</div>';
				}

			} else {

				if ($givenOption === 1) {
					echo '<div style="color:red;">' . $block->escapeHtml($message) . '</div>';
				} elseif ($givenOption === 2) {
					echo '<div style="color:red;">This item will be issued by school</div>';
				}

			}
            ?>
		  </td>
        <?php endif; ?>
        <td class="col-status">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $_item->getStatus() ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price-original">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $block->displayPriceAttribute('original_price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'price') ?>
            <?php else: ?>
                    &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-ordered-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyInvoiced()): ?>
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Invoiced') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyInvoiced()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyShipped() && $block->isShipmentSeparately($_item)): ?>
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyShipped()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyRefunded()): ?>
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Refunded') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyRefunded()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyCanceled()): ?>
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Canceled') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyCanceled()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($block->isShipmentSeparately($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Ordered') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyShipped()): ?>
                    <tr>
                        <th><?= /* @escapeNotVerified */ __('Shipped') ?></th>
                        <td><?= /* @escapeNotVerified */ $_item->getQtyShipped()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'subtotal') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-amount">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $block->displayPriceAttribute('tax_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-percent">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $block->displayTaxPercent($_item) ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discont">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @escapeNotVerified */ $block->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'total') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if($_showlastRow): ?>
    <tr<?php if (!$block->canDisplayGiftmessage()) echo ' class="border"' ?>>
        <td class="col-product">
            <?php if ($block->getOrderOptions()): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions() as $option): ?>
                    <dt><?= /* @escapeNotVerified */ $option['label'] ?>:</dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= /* @escapeNotVerified */ $option['value'] ?>
                    <?php else: ?>
                        <?= $block->truncateString($option['value'], 55, '', $_remainder) ?>
                        <?php if ($_remainder):?>
                            ... <span id="<?= /* @escapeNotVerified */ $_id = 'id' . uniqid() ?>"><?= /* @escapeNotVerified */ $_remainder ?></span>
                            <script>
require(['prototype'], function(){

    $('<?= /* @escapeNotVerified */ $_id ?>').hide();
    $('<?= /* @escapeNotVerified */ $_id ?>').up().observe('mouseover', function(){$('<?= /* @escapeNotVerified */ $_id ?>').show();});
    $('<?= /* @escapeNotVerified */ $_id ?>').up().observe('mouseout',  function(){$('<?= /* @escapeNotVerified */ $_id ?>').hide();});
                            
});
</script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
