<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
use Magento\Framework\App\Action\Action;
use Magento\Framework\Data\Helper\PostHelper;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

/** @var \Ubertheme\UbThemeHelper\Helper\Data  $ubHelper */
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = $block->escapeHtml(__($block->getTitle()));
    
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    $widgetId = $block->getData('page_var_name');
    $itemClass = "product-widget-item";
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */
    $mode ?>">
        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content" id="<?= $widgetId ?>">
            <?= /* @noEscape */
            '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */
            $mode ?> <?= /* @noEscape */
            $mode ?>">
                <ol class="list product-items <?= /* @noEscape */
                $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php
                        //get category names of product
                        $categoryNames = $ubHelper->getProductOptionTextByAttribute($_item, 'categories');
                        //get discount percent info
                        $discountPercent = $ubHelper->getDiscountPercent($_item);
                        ?>

                        <?= /* @noEscape */
                        ($iterator++ == 1) ? '<li class="product-item ' . $itemClass . '">' : '</li><li class="product-item ' . $itemClass . '">' ?>
                        <div class="product-item-info">
                            <div class="photo-item">
                                <div class="wrap-new-sale">
                                    <?php if($_item->getIsHot()): ?>
                                        <span class="hot-label icon-label"><?=__('hot')?></span>
                                    <?php endif; ?>

                                    <?php if ($discountPercent) : ?>
                                        <span class="sale-label icon-label"> <?php echo "- {$discountPercent}%"; ?></span>
                                    <?php endif; ?>

                                    <?php if ($ubHelper->asNewProduct($_item)) : ?>
                                        <span class="new-label icon-label"><?php echo __("New"); ?></span>
                                    <?php endif; ?>
                                </div>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <a href="#" class="action tocart" style="display: none !important; opacity: 0 !important; visibility: hidden !important;">
                                        <?= $block->escapeHtml(__('Add to Cart')) ?>
                                    </a>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                        <a href="#"
                                           data-post='<?= /* @noEscape */
                                           $block->getAddToWishlistParams($_item) ?>'
                                           class="action towishlist" data-action="add-to-wishlist"
                                           title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */
                                        $compareHelper->getPostDataParams($_item) ?>'
                                           title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="product-item-details">
                                <h5 class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h5>
                                <?php if ($categoryNames): ?>
                                    <h4 class="catalog-category-name"><?= $categoryNames ?></h4>
                                <?php endif; ?>
                                <div class="details">
                                    <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($showCart): ?>
                                    <div class="product-item-actions">
                                        <?= $block->getProductDetailsHtml($_item) ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available">
                                                        <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable">
                                                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
<?php
$isShowPage = $block->showPager();
//We are only support infiniteScroll process when enabled pager in widget
if ($isShowPage) {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    /** @var \Ubertheme\UbThemeHelper\Block\InfiniteScroll\Initial $blockInfiniteScroll */
    $blockInfiniteScroll = $objectManager->get('Ubertheme\UbThemeHelper\Block\InfiniteScroll\Initial');
    $isEnable = $blockInfiniteScroll->isEnable();
    $urlImageLoading = $blockInfiniteScroll->getLoaderImageURL();
    $textLoadingMore = $blockInfiniteScroll->getLoadingMoreText();
    $textNoMoreItems = $blockInfiniteScroll->getNoMoreItemsText();
    $textButton = $blockInfiniteScroll->getButtonText();
    $htmlImgLoading = ($urlImageLoading) ? '<img src="' . $urlImageLoading . '" alt=" '. __("Image Loading") .'" />' : '';
    $htmlLoader = '<div class="page-load-status">' .
        '<div class="infinite-scroll-request">' . $htmlImgLoading . __($textLoadingMore) . '</div>' .
        '<p class="infinite-scroll-error infinite-scroll-last">' . __($textNoMoreItems) . '</p>' .
        '</div>';
    $btnLoadMore = '<div class="load-mode-button"><button class="load-more-button">' . __($textButton) . '</button></div>';
}
?>
<script>
    require([
        'jquery',
        'Ubertheme_UbThemeHelper/js/jquery.infiniteScroll'
    ], function ($, infiniteScroll, catalogAddToCart) {

        $(document).ready(function () {

            //Bind infiniteScroll
            <?php if ($isShowPage && $isEnable): ?>

            // Hide pager
            $("#<?= $widgetId ?> .pager").hide();

            var widgetId = '<?= $widgetId ?>',
                itemClass = '<?= $itemClass ?>',
                $btnNext = $("#<?= $widgetId ?> .next"),
                $container = $("#<?= $widgetId ?> .products-grid");
            if ($btnNext.length) {
                $container.append('<?= $htmlLoader ?>');
                $container.append('<?= $btnLoadMore ?>');
                $(".page-load-status").hide();

                // Initial infiniteScroll
                var $infScroll = new infiniteScroll('#' + widgetId + ' .list', {
                    path: function () {
                        return $btnNext.attr("href");
                    },
                    append: '#' + widgetId + ' .' + itemClass,
                    status: '#' + widgetId + ' .page-load-status',
                    button: '#' + widgetId + ' .load-more-button',
                    history: false,
                    loadOnScroll: false,
                });

                $infScroll.on('load', function (response, path) {
                    var $btnLoadMore = $('#' + widgetId + ' .load-more-button'),
                        $statusEl = $('#' + widgetId + ' .page-load-status'),
                        $finishedEl = $('#' + widgetId + ' .infinite-scroll-last');
                    var url = path.slice(0, -1),
                        currentPage = path.substr(path.length - 1),
                        nextPage = url + parseInt(parseInt(currentPage) + 1);
                    if ($("#" + widgetId + " a[href='" + nextPage + "']").length) {
                        $("#" + widgetId + " .next").attr("href", nextPage);
                        $btnLoadMore.show();
                    } else {
                        $btnLoadMore.hide();

                        setTimeout(function () {
                            $statusEl.addClass("finished").show();
                            $finishedEl.addClass("finished").show();
                        }, 300);

                        setTimeout(function () {
                            $statusEl.fadeOut(2000);
                        }, 3000);
                    }
                });

                // After rendered items actions
                $infScroll.on('append', function (response, path, items) {
                    // Initial quickview
                    if ($('body').UBQuickView && ubQuickViewOptions !== undefined) {
                        $.ub.UBQuickView(ubQuickViewOptions);
                    }
                    //Bind ajax add cart functions for newly loaded items
                    if ($('body').AjaxAddCart && ubAjaxCartOptions !== undefined) {
                        $.ub.AjaxAddCart(ubAjaxCartOptions);
                    }
                });

                $infScroll.on('request', function (path) {
                    $('#' + widgetId + ' .load-more-button').hide();
                })
            }

            <?php endif; ?>
        });
    });
</script>

