<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
/** @var \Ubertheme\UbThemeHelper\Helper\Data  $ubHelper */
$ubHelper = $this->helper('Ubertheme\UbThemeHelper\Helper\Data');

//Check and build custom CSS classes
$customClasses = [];
if (!(bool) $ubHelper->getParam('category_view/general/add_to_cart')) {
    $customClasses[] = 'hide-add-to-cart';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_compare')) {
    $customClasses[] = 'hide-add-to-compare';
}
if (!(bool) $ubHelper->getParam('category_view/general/add_to_wishlist')) {
    $customClasses[] = 'hide-add-to-wishlist';
}
if (!(bool) $ubHelper->getParam('category_view/general/rating')) {
    $customClasses[] = 'hide-rating';
}
if (!(bool) $ubHelper->getParam('category_view/general/price')) {
    $customClasses[] = 'hide-price';
}
if (!(bool) $ubHelper->getParam('category_view/general/show_author')) {
    $customClasses[] = 'hide-author';
}
if (!(bool) $ubHelper->getParam('category_view/general/swatches')) {
    $customClasses[] = 'hide-swatches';
}
$customClasses = implode(' ', $customClasses);


if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_images_only_widget';
    $title = $block->escapeHtml(__($block->getTitle()));
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?= /* @escapeNotVerified */ $mode ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
        </div>
        <div class="block-content">
            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @escapeNotVerified */ $mode ?> <?= /* @escapeNotVerified */ $mode ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type.' '.$customClasses ; ?>">
                    <?php foreach ($items as $_item): ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <div class="item-photo">
                                <?php
                                    $ubLabel = $ubHelper->getProductOptionTextByAttribute($_item, 'ub_label');
                                    $ubAuthor = $ubHelper->getProductOptionTextByAttribute($_item, 'ub_author');
                                ?>
                                <div class="ub-icon-label label-<?php echo strtolower(str_replace(' ', '', $ubLabel));?>"><?php echo $ubLabel; ?></div>
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                            </div>
                            <div class="product-item-details">
                                <h5 class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h5>
                                <div class="ub-author"><?= $ubAuthor; ?></div>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
                                <?= $block->getProductPriceHtml($_item, $type); ?>
                            </div>
                        </div>
                     </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
