<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/* @var $block \Magento\Framework\View\Element\Template */


$blockObj= $block->getLayout()->createBlock('Retailinsights\Registers\Block\Index\Header');
 ?>
<!-- 
<div class="header_logo_display">
    <a href="<?php //echo $blockObj->getCustUrl().'schools'; ?>">
        <img src="<?php //echo $blockObj->getCustUrl(); ?>pub/media/ubertheme/school_zone/logo-centralbooks.png">
      </a>
      <block class="Magento\Checkout\Block\Cart\Sidebar" name="minicart" as="minicart" after="logo" template="cart/minicart.phtml">
      <?php
	//	echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/quicklogin.phtml")->toHtml();
		//echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/quickregister.phtml")->toHtml();
		//echo $this->getLayout()->createBlock('Magento\Checkout\Block\Cart\Sidebar')->setTemplate('Magento_Checkout::cart/minicart.phtml')->toHtml();
		// echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Checkout::cart/minicart.phtml")->toHtml();
		//echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/quickaccess.phtml")->toHtml();
      ?>
</div>

 -->