<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$_product = $block->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
  $customerSession = $objectManager->create('Magento\Customer\Model\Session');
  ?>
<?php if ($block->canEmailToFriend()): 
  $href = ($customerSession->isLoggedIn()) ? $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) : '#';

?>
    <div class="product-mailto-links" data-role="mail-to-links">
                <a href="<?php /* @escapeNotVerified */ echo $href ?>"
                    class="action towishlist mailto friend"><i class="fa fa-envelope"></i>
                    <span><?php /* @escapeNotVerified */ echo __('Email to a Friend') ?></span>
                </a>
            
    </div>
    
<?php endif; ?>


