<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()): ?>
    <div class="product-mailto-links" data-role="mail-to-links">
                <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
                    class="action towishlist mailto friend"><i class="fa fa-envelope"></i>
                    <span><?php /* @escapeNotVerified */ echo __('Email to a Friend') ?></span>
                </a>
            
    </div>
    
<?php endif; ?>
