<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<div class="has-toggle minicart" id="minicart" data-block="minicart">
  <div class="btn-toggle" data-bind="scope: 'minicart_content'">
        <span class="fa fa-shopping-cart"></span>
        <span class="text"><?= /* @escapeNotVerified */ __('Shopping Cart') ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
              <!-- ko i18n: '(' --><!-- /ko -->
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'item(s)' --><!-- /ko -->
            <!-- /ko -->
            </span>
            <!-- ko i18n: ')' --><!-- /ko -->
        </span>
  </div>
  <div class="inner-toggle" id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
      <?php if ($block->getIsNeedToDisplaySideBar()): ?>
          <!-- ko template: getTemplate() --><!-- /ko -->
          <?= $block->getChildHtml('minicart.addons') ?>
      <?php endif ?>
  </div>


    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
     /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>
