<?php
    $drivers = $block->getAutoDrivers();

    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $persistor = $om->get('Magento\Framework\App\Request\DataPersistorInterface');
    $colorOption = $persistor->get('coloroption');

    $url = $block->getBaseUrl();
    $url = $url."cbsadmin/processcboorders/processcboshippingorders/UploadCsv";
?>
<div class="processcbo">
    <div class="cboBarcodeScanning">
        <div class="panel panel-default">
            <div class="panel-heading">CBO Barcode Scanning Section</div>
            <div class="panel-body">
                <table> 
                    <tr>
                        <td><label>CBO Order Number</label></td>
                        <td><input type="text" id="txtCboOrderId"/></td>
                        <td><input type="button" id="btnCheckOrderId" value="Add"/>
                        <!-- <td><label class="note">Note: Only 10 Orders will be allowed for transaction here</label></td> -->

                        <td>
                            <div class="import-shipping">
                              <div class="header">
                                <h4>CSV File:</h4>
                              </div>
                              <form class="import-shipping-form" name="form" id="form" action="<?= $url ?>" method="POST" enctype="multipart/form-data">
                                <?php echo $block->getBlockHtml('formkey'); ?>
                                <input type="file" required class="required-entry" name="csv" />
                                <button type="submit">Import</button>
                              </form>
                             
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $block->getBaseUrl()."media/ubertheme/csvSamples/cboOrderSamples.csv"; ?>">
                              <span class="sample_csv_cbo">Download Sample Csv</span>
                            </a>
                        </td>
                    </tr>
                </table>
                <div>
                    <span id="duplicate"></span>
                </div>
                <div>
                    <span id="readyToSubmit"></span>
                </div>

                <div>
                    <?php 
                    if($colorOption != ''){
                        ?>
                        <label id="test" ></label>
                        <?php
                        $size = sizeof($colorOption); ?>
                        <label id="orderIdListTest"> <?php
                            foreach ($colorOption as $key => $value) {
                               echo $value;
                        }
                        ?>
                        </label>
                        <script>
                            require(['jquery'], function($){
                                 'use strict';
                                    $("#btnOrderSubmit").hide();
                                    $('#tdBtnSubmit').append('<input type="button" id="btnOrderSubmit" class="inside_csv" value="Submit"/>');

                            });
                        </script>
                   <?php }else{
                        ?>  <label id="orderIdList"></label><br> <?php
                    }
                    ?>
                    </div>
                <span id="tdBtnSubmit"></span>
                
                <span id="checkall"></span>
                <span id="uncheckall"></span>
                <p id="order_count_box">total orders Are ready to assign : <span id="order_count"></span></p>
                <p id="order_count_box_success">Succesfully assigned orders : <span id="order_count_success"></span></p>
                <div id="orderListStatus">
                    <span></span>
                </div>
                <div id="orderListStatusSuccess">
                    <span></span>
                </div>
            </div>
        </div>
    </div>
    <div class="autoCourier">
        <h2>Please Select Auto Courier Services / Other Courier</h2>
        <label class="note">Note: Only valid orders will be assigned to (Auto Courier) / (Other Couriers)</label>
        <div class="panel panel-default">
            <div class="panel-heading">Auto Courier Services</div>
            <div class="panel-body">
                <table> 
                    <tr>
                        <td><select id="driverList"><option value="0">Select The Auto Driver</option>
                        <?php foreach($drivers as $driver){
                            ?>
                            <option value="<?php echo $driver['id'] ?>"><?php echo $driver['driver_name'] ?></option>
                        <?php    }?>
                        </select></td>
                        <td><input type="button" id="btnSubmitAutoDriver" value="Submit"/>
                    </tr>
                </table>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Other Couriers</div>
            <div class="panel-body">
                <table> 
                    <tr>
                        <td><label>Tracking Title</label></td>
                        <td><input type="text" id="txtTrackingTitle"/></td>
                        <td><label>Tracking Number</label></td>
                        <td><input type="text" id="txtTrackingNumber"/></td>
                        <td><input type="button" value="Submit" id="btnSubmitOtherCouriers"/></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td><label class="note">Will be same for multiple orders</label></td>
                        <td></td>
                        <tr></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<?php 
   $persistor->set('coloroption', '');
?>
<style>
.processcbo .panel-default{
    border: 1px solid black;
    margin-bottom: 20px;
}
.processcbo .panel-heading{
    background-color: #6f8992;
    padding: 2px 10px;
    color: white;
    font-weight: 700;
}
.processcbo .panel-body{
    padding: 10px;
}
.processcbo .panel-body table tbody tr td{
    padding: 0 40px 0 0;
}
.processcbo label.note{
    color: red;
}
.processcbo .panel-body table{
    margin-top: 5px;
}
.processcbo select{
    padding: 0 5px;
}
.processcbo .autoCourier{
    display: none;
}
</style>
<script>
require(['jquery'], function($){
    'use strict';
     $("#order_count_box").hide();
     $("#order_count_box_success").hide();

     $('#checkall').click(function(){
         $(".group").prop('checked', true);
     });
     $('#uncheckall').click(function(){
         $(".group").prop('checked', false);
     });

    $('#btnOrderSubmit').click(function(){
                $(".group1").remove();

                var valid_ids = $('.valid_ids').val();
                var data='';
                $("li label span").each(function(){
                    var $val= $(this).text();
                    data +=$val+',';

                });
                console.log(data);
                var orderIds = $('#orderIdList').html();
                var orderArray = data.split(',');


                var base_url = document.location.origin+"/cbsadmin/processcboorders/processcboshippingorders/CheckShippment";

            var param={ orderIds: orderArray}
            $.ajax({
                url: base_url,
                type: "POST",
                data: param,
                dataType: "json",
                complete:function(response){
                    var obj = response.responseJSON;
                    
                    $("#btnOrderSubmit").hide();
                            $(".assign_courier").remove();
                            $(".dispatch_courier").remove();
                            $(".assign_delivered").remove();
                            $(".assign_pending").remove();

                            $('#checkall').append('<input type="button" id="checkall" value="Check All"/>');
                            $('#uncheckall').append('<input type="button" id="uncheckall" value="Uncheck All"/>');
                    var count =0;
                    for(var index in obj) {
                        if(index != ''){
                            if(obj[index] == 'yes'){
                                count++
                                $('#orderListStatus').append('<label><input type="checkbox" class="group" name="language" value="'+index
                                    +'">'+index+' : Assign Couriers</label><br/>');                            
                                $('.autoCourier').show();
                            }
                            if(obj[index] == 'dispatched_to_courier'){
                                 $('#orderListStatus').append('<label><input class="group1" type="checkbox" name="language" value="'+index
                                    +'"disabled>'+index+' : dispatched_to_courier / Courier selection may be pending</label><br/>');
                            }
                            if(obj[index] == 'order_delivered'){
                                 $('#orderListStatus').append('<label><input class="group1" type="checkbox" name="language" value="'+index
                                    +'"disabled>'+index+' : order_delivered / Courier selection may be pending</label><br/>');
                            }
                            if(obj[index] == 'no order id'){
                                 $('#orderListStatus').append('<label><input class="group1" type="checkbox" name="language" value="'+index
                                    +'"disabled>'+index+' : Processing / Courier selection may be pending</label><br/>');
                            }
                            if(obj[index] == 'no'){
                                 $('#orderListStatus').append('<label><input class="group1" type="checkbox" name="language" value="'+index
                                    +'"disabled>'+index+' : Processing / Courier selection may be pending</label><br/>');
                            }
                            if(obj[index] == 'no_tracking_info'){
                                 $('#orderListStatus').append('<label><input class="group1" type="checkbox" name="language" value="'+index
                                    +'"disabled>'+index+' : Courier tracking info not exists</label><br/>');
                            }
                            if(obj[index] == 'no_pay_slip_generated'){
                                 $('#orderListStatus').append('<label><input class="group1" type="checkbox" name="language" value="'+index
                                    +'"disabled>'+index+' : Package slip not downloaded</label><br/>');
                            }
                        }
                    }
                     $("#order_count_box").show()
                    $("#order_count").text(count);
                },
                error:function(xhr,status,errorThrown){
                }
            });

        });

       $('#btnCheckOrderId').on('click', function(){
        // check for limit 10
        var orderId = $('#txtCboOrderId').val();

        var orderArrayID = orderId.split(',');

        // console.log('orderId'+orderId)
        // console.log('orderArrayID'+orderArrayID)

        if((orderId.empty()) || (orderId.length < 9)){
            alert('Please provide valid order id');
            return;
        }
        
        var orderIds = $('#orderIdList').html();
        var orderArray = orderIds.split(',');
      
        for (var i = 0; i < orderArray.length; i++) {
            if($.trim(orderArray[i]) == $.trim(orderId)){
                alert($.trim(orderId)+' : Order ID Already Scanned');
                return;
            }
        }
        for (var i = 0; i < orderArray.length; i++) {
            for (var j = 0; j < orderArrayID.length;j++) {
                if($.trim(orderArray[i]) == $.trim(orderArrayID[j])){
                    alert($.trim(orderArrayID[j])+' : Order ID Already Scanned');
                    return;
                }
            }
        }
        var orderIdsReady= {};
             var indexReady = [];
        $( "#readyToSubmit span" ).each(function( index ) {
            indexReady = $( this ).text().split(':');

        });
            // if($.trim(indexReady[0]) == $.trim(orderId)){
            //     alert($.trim(indexReady[0])+' : Order ID Already Scanned');
            //     return false;
            // }

            // for (var i = 0; i < orderIdsReady.length; i++) {
                // if($.trim(indexReady[0][i]) == $.trim(orderId)){
                //     alert($.trim(orderId)+' : Order ID Already Scanned');
                //     return;
                // }
            // }




        if($('#orderIdList').html()){
           
            var orderArray = orderId.split(',');

                var base_url = document.location.origin+"/cbsadmin/processcboorders/processcboshippingorders/CheckShippment";
                var param={ orderIds: orderArray}
                $.ajax({
                url: base_url,
                type: "POST",
                data: param,
                dataType: "json",
                showLoader: true,
                complete:function(response){
                    var obj = response.responseJSON;
                    for(var index in obj) {
                         if(index != ''){
                             if(obj[index] == 'yes'){
                                $('#orderIdList').append(','+index);
                            }
                            if(obj[index] == 'dispatched_to_courier'){
                                  $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : dispatched_to_courier / Courier selection may be pending</span><br/>');
                            }
                            if(obj[index] == 'order_delivered'){
                                  $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : order_delivered / Courier selection may be pending</span><br/>');
                            }
                            if(obj[index] == 'no order id'){
                                  $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Processing / Courier selection may be pending</span><br/>');
                                
                            }
                            if(obj[index] == 'no'){
                                 $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Processing / Courier selection may be pending</span><br/>');
                            }
                            if(obj[index] == 'no_tracking_info'){
                                 $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Courier tracking info not exists</span><br/>');
                            }
                            if(obj[index] == 'no_pay_slip_generated'){
                                 $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Package slip not downloaded</span><br/>');
                            }
                        }
                    }
                },
                error:function(xhr,status,errorThrown){
                }
            });
        }else{
                var orderArray = orderId.split(',');
                var orderArrayFirstScan = orderArray;
                var base_url = document.location.origin+"/cbsadmin/processcboorders/processcboshippingorders/CheckShippment";
                var param={ orderIds: orderArray}
                $.ajax({
                url: base_url,
                type: "POST",
                data: param,
                dataType: "json",
                showLoader: true,
                complete:function(response){
                    var obj = response.responseJSON;
                    for(var index in obj) {
                         if(index != ''){
                             if(obj[index] == 'yes'){
                                $('#orderIdList').append(index+',');
                            }
                            if(obj[index] == 'dispatched_to_courier'){
                                  $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : dispatched_to_courier / Courier selection may be pending</span><br/>');
                            }
                            if(obj[index] == 'order_delivered'){
                                  $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : order_delivered / Courier selection may be pending</span><br/>');
                            }
                            if(obj[index] == 'no order id'){
                                  $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Processing / Courier selection may be pending</span><br/>');
                                
                            }
                            if(obj[index] == 'no'){
                                 $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Processing / Courier selection may be pending</span><br/>');
                            }
                            if(obj[index] == 'no_tracking_info'){
                                 $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Courier tracking info not exists</span><br/>');
                            }
                            if(obj[index] == 'no_pay_slip_generated'){
                                 $('#readyToSubmit').append('<span class="group1">'+index+
                                    ' : Package slip not downloaded</span><br/>');
                            }
                        }
                    }    
                },
                error:function(xhr,status,errorThrown){
                }
            });

            $("#btnOrderSubmit").hide();
            
         

            $('#tdBtnSubmit').append('<input type="button" id="btnOrderSubmit" class="inside" value="Submit"/>');

            // $('#orderIdList').append(orderId);
            // $("#btnOrderSubmit").hide();

            $('#btnOrderSubmit').on('click', function(){
                $("input.group1").prop("disabled", true);

                var orderIds = $('#orderIdList').html();
                var orderIds = orderIds.replace(' ', '');
                var orderArray = orderIds.split(',');

                var base_url = document.location.origin+"/cbsadmin/processcboorders/processcboshippingorders/CheckShippment";

            var param={ orderIds: orderArray}
            $.ajax({
                url: base_url,
                type: "POST",
                data: param,
                dataType: "json",
                complete:function(response){
                    var obj = response.responseJSON;
                    $("#btnOrderSubmit").hide();
                    
                    $('#checkall').append('<input type="button" id="checkall" value="Check All"/>');
                    $('#uncheckall').append('<input type="button" id="uncheckall" value="Uncheck All"/>');
                    var count=0;
                    for(var index in obj) {
                        if(obj[index] == 'yes'){
                            count++;

                            $('#orderListStatus').append('<label id="assign_orders"><input type="checkbox" class="group" name="language" value="'+index
                                +'">'+index+' : Assign Couriers</label><br/>');
                            $('.autoCourier').show();
                        }
                    }
                    $("#order_count_box").show()
                    $("#order_count").text(count);
                },
                error:function(xhr,status,errorThrown){
                }
            });

            });
        }
        $('#txtCboOrderId').val('');
    });

    $('#btnSubmitOtherCouriers').on('click', function(){
        console.log('other couriers');
        var base_url = document.location.origin+"/cbsadmin/walkincustomers/processothercouriers/AssignOtherCouriers";
        var orderIds = {};

        var arr = [];
        $.each($("input[name='language']:checked"), function(){
               arr.push($(this).val());
        });
        orderIds = arr;
        var trackingTitle = $('#txtTrackingTitle').val();
        var trackingNumber = $('#txtTrackingNumber').val();

        var param={ orderIds: orderIds,
            trackingTitle: trackingTitle,
            trackingNumber: trackingNumber
                }
        $.ajax({
            url: base_url,
            type: "POST",
            data: param,
            dataType: "json",
            complete:function(response){
                var obj = response.responseJSON;
                for(var index in obj) {
                    if(obj[index] == 'success'){
                        $('#orderListStatus').append('<span>'+index
                                +' : Success</span><br/>');
                            $('.autoCourier').hide();
                    }
                }
                
            },
            error:function(xhr,status,errorThrown){
            }
        });
    });

    
    $('#btnSubmitAutoDriver').on('click', function(){
        var base_url = document.location.origin+"/cbsadmin/processcboorders/processcboshippingorders/AssignDriver";
        // console.log(base_url);
        var orderIds = {};

            var arr = [];
            $.each($("input[name='language']:checked"), function(){
                   arr.push($(this).val());
                   console.log($(this).val());
            });
            orderIds = arr;
            
        var driverId = $('#driverList option:selected').val();

        if(driverId == '0'){
            alert('Please select driver');
            return;
        }

         if(orderIds.length == 0){
            alert('Please select Order');
            return;
        }

        var param={ orderIds: orderIds,
                    driverId: driverId
                }
        $.ajax({
            url: base_url,
            type: "POST",
            data: param,
            showLoader: true,
            dataType: "json",
            complete:function(response){
                var count=0;
                var obj = response.responseJSON;
                $('#orderListStatus').remove();
                for(var index in obj) {
                    if(obj[index] == 'success'){
                        count++;
                        $('#orderListStatusSuccess').append('<span>'+index
                                +' : Success</span><br/>');
                            $('.autoCourier').hide();
                    }
                }
                $("#order_count_box_success").show()
                $("#order_count_success").text(count);
            },
            error:function(xhr,status,errorThrown){
            }
        });
    });
});
</script>
