<?php
    $params = $this->getRequest()->getParams();
    $orderIds = json_decode($params['id']);
    $orderDetails = $block->getOrderStatus($orderIds[0]);
    $shippingAddress = $orderDetails->getShippingAddress()->getData();
    $shippingAddressCountry = $block->getCountryName($shippingAddress['country_id']);
    $billingAddress = $orderDetails->getbillingAddress()->getData();
    $payment = $orderDetails->getPayment();

	$hasBundleItem = false;
	foreach ($orderDetails->getAllItems() as $item) {
		if ($item->getProductType() === 'bundle') {
			$hasBundleItem = true;
			break;
		}
	}

	if ($hasBundleItem) {
		$orderItems = $orderDetails->getAllVisibleItems();
	} else {
		$orderItems = $orderDetails->getAllVisibleItems();
		$firstItem = reset($orderItems);
	}

    //$validServiceTypes = json_decode($block->getServiceTypes(), true);

    $validServiceTypes = json_decode($block->getLocalServiceTypes(), true);

    $allAddresses = json_decode($block->getAddresses(), true);
    $restrict_num_pieces_modification = $this->helper('Shipsy\EcommerceExtension\Helper\Data')->getConfig('store','shipsy_optional_settings/optional_settings/shipsy_restrict_num_pieces_input_modification') ? true : false;
    $authDetailsFromCookies = $block->getAuthDetailsFromCookies();

    // var_dump($shippingAddress);
if (!array_key_exists('error', $allAddresses) && !array_key_exists('error', $validServiceTypes)) {
    $forwardAddress = $allAddresses['forwardAddress'];
    $reverseAddress = $allAddresses['reverseAddress'];
    $exceptionalReturnAddress = $allAddresses['exceptionalReturnAddress'];
    $returnAddress = $allAddresses['returnAddress'];
    $showW3wInput = $block->getW3wConfig() == '1';
    ?>
<form action="<?php echo $block->getUrl('softdatasync/softdatashipsy/formdata'); ?>" method="post">
<input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
    <div class="form-group" id="order-details" style = "padding : 15px">
        <div class  ="header-style" style = "width : 90% !important">
            <span class = "header-font">Order Details</span>
        </div>
        <div class="container" style = "margin-left : 0px">
            <div class="row">
                <div class="col-sm-4">
                <label for="textInput" class= "label-font">Order Number <span class = "required-text">*</span></label>
                 <input type="text" id="customer-reference-number" name="customer-reference-number" class="form-control form-control-lg "
                 style = "border-radius : 0px" value="<?php echo $orderDetails->getIncrementId() ?>">
                 <input type="hidden" name="order-id" value="<?php echo $orderIds[0] ?>"/>
                 <div class="orderText" style = "color : red ; font-size : 10px;display:none"> Order Number is required</div>
                </div>
                <div class="col-sm-4" >
                <label for="textInput" class = "label-font">AWB Number</label>
                <input type="text" name="awb-number" id="awb-number" class="form-control form-control-lg " style = "border-radius : 0px"  placeholder="Text input">
                </div>
                <div class="col-sm-4">
                    <label for="select" class= "label-font">Service Type <span class = "required-text">*</span></label>
                    <select class="custom-select" name="service-type" id="select-service-type" style = "border-radius : 0px; height : 33px; font-size:12px"  >
                    <?php foreach ($validServiceTypes as $serviceType) { ?>  
                        <option value="<?php echo $serviceType['code'] ?>" selected = ""><?php echo $serviceType['name'] ?></option>
                    <?php } ?>
                    </select>  
                </div>
             </div>
             <div class="row mt-4">
                <div class="col-sm-4" >
                    <label for="select" class = "label-font">Courier Type <span class = "required-text">*</span></label>
                    <select class="custom-select " name="courier-type" id="select-courier-type"
                    style = "border-radius : 0px; height : 33px; font-size:12px">
                        <option value="NON-DOCUMENT" selected>NON-DOCUMENT</option>
                        <option value="DOCUMENT">DOCUMENT</option>
                    </select>
                </div>
                <div class="col-sm-4" >      
                    <label for="select" class = "label-font">Consignment Type <span class = "required-text">*</span></label>
                    <select class=" custom-select" name="consignment-type" id="select-consignment-type"
                    style = "border-radius : 0px; height : 33px; font-size:12px">
                        <option value="forward" selected>FORWARD</option>
                        <option value="reverse">REVERSE</option>
                    </select>
                </div>
                <div class="col-sm-4">
                     <label for="num-pieces" class = "label-font">Number of Pieces <span class = "required-text">*</span></label>
                        <input type="text" id="num-pieces"  style = "border-radius : 0px" name="num-pieces" class="form-control form-control-lg " value="<?php echo count($orderItems) ? 1: count($orderItems); ?>" <?php echo ($restrict_num_pieces_modification) ? 'readonly' : ''; ?> >
                        <div class="numpiecesError" style = "color : red ; font-size : 10px;display:none"> Value should be greater than 0</div>
                        <!---<div class= "form-check" style = " margin-top:8px">
                        <input class="form-check-input"  style = "border-radius : 0px" type="checkbox" name="multiPieceCheck" value="true" id="multiPieceCheck">
                        <label class="form-check-label label-font" for="multiPieceCheck" style = "margin-left:10px;font-size:12px !important">All pieces same</label>
                        </div>-->
                </div>
             </div>
        </div>
    </div>

    <div class="form-group" id="origin-details" style = "padding:15px">
        <div class  ="header-style" style = "width : 90% !important" >
            <span class = "header-font">Origin Details</span>
        </div>
        <div class="container" style = "margin-left : 0px">
            <div class="row">
                    <div class="col-sm-4" >
                        <label for="origin-name" class= "label-font">Name <span class = "required-text">*</span></label>
                         <input type="text" id="origin-name" style = "border-radius : 0px"  name="origin-name" class="form-control form-control-lg  " value="<?php echo $forwardAddress['name']; ?>">
                         <div class="nameErrorText" style = "color : red ; font-size : 10px;display:none"> Origin Name is required</div>
                        </div>
                    <div class="col-sm-4" >      
                            <label for="origin-number" class = "label-font">Phone Number <span class = "required-text">*</span></label>
                            <input type="number" id="origin-number" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" style = "border-radius : 0px"  name="origin-number" class="form-control form-control-lg " value="<?php echo $forwardAddress['phone'] ?>">
                            <div class="phoneErrorText" style = "color : red ; font-size : 10px;display:none"> Phone number is required</div>
                        </div>
                    <div class="col-sm-4">               
                          <label for="origin-alt-number" class= "label-font">Alternate Phone Number</label>
                          <input type="number" id="origin-alt-number" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" style = "border-radius : 0px"  name="origin-alt-number" class="form-control form-control-lg " value="<?php echo $forwardAddress['alternate_phone'] ?>">
                    </div>
             </div>
             <div class = "row mt-4">
                    <div class="col-sm-6" >
                        <label for="origin-line-1" class= "label-font">Address Line 1 <span class = "required-text">*</span></label>
                        <input type="text" id="origin-line-1" style = "border-radius : 0px"  name="origin-line-1" class="form-control form-control-lg " value="<?php echo $forwardAddress['address_line_1'] ?>">
                        <div class="addressErrorText" style = "color : red ; font-size : 10px;display:none"> Origin Address is required</div>

                    </div>
                    <div class="col-sm-6">               
                          <label for="origin-line-2" class = "label-font">Address Line 2</label>
                            <input type="text" id="origin-line-2" style = "border-radius : 0px"  name="origin-line-2" class="form-control form-control-lg " value="<?php echo $forwardAddress['address_line_2'] ?>">
                    </div>
            </div>
            <div class  = "row mt-4"> 
                    <div class="col-sm-3" >
                         <label for="origin-city" class= "label-font"> City <span class = "required-text">*</span></label>
                        <input type="text" id="origin-city" name="origin-city" style = "border-radius : 0px"  class="form-control form-control-lg " value="<?php echo $forwardAddress['city'] ?>">
                        <div class="cityErrorText" style = "color : red ; font-size : 10px;display:none">Origin City is required</div>
                    </div>
                     <div class="col-sm-3" >
                         <label for="origin-state" class = "label-font">State <span class = "required-text">*</span></label>
                         <input type="text" id="origin-state" name="origin-state" style = "border-radius : 0px"  class="form-control form-control-lg " value="<?php echo $forwardAddress['state'] ?>">
                         <div class="stateErrorText" style = "color : red ; font-size : 10px;display:none">Origin State is required</div>
                        </div>
                     <div class="col-sm-2" >
                        <label for="origin-country" class = "label-font">Country <span class = "required-text">*</span></label>
                        <input type="text" id="origin-country" style = "border-radius : 0px" name="origin-country" class="form-control form-control-lg " value="<?php echo $forwardAddress['country'] ?>">
                        <div class="countryErrorText" style = "color : red ; font-size : 10px;display:none">Origin Country is required</div>

                    </div>
                     <div class="col-sm-2" >
                        <label for="origin-pincode">Pincode</label>
                        <input type="text" id="origin-pincode" style = "border-radius : 0px"  name="origin-pincode" class="form-control form-control-lg " value="<?php echo $forwardAddress['pincode'] ?>">
                        <div class="pincodeErrorText" style = "color : red ; font-size : 10px;display:none">Origin Pincode is required</div>
                    </div>
                    <?php if ($showW3wInput): ?>
                    <div class="col-sm-2" >
                        <label for="origin-what3word-code">What3Word Code</label>
                        <input type="text" placeholder="Eg. fizzle.clip.quota" id="origin-what3word-code" oninput="this.value" style = "border-radius : 0px"  name="origin-what3word-code" class="form-control form-control-lg " value="<?php echo $forwardAddress['w3w_code']?>">
                    </div>
                    <?php endif; ?>
            </div>  
        </div>
    </div>
    <div class="form-group" id="destination-details"  style = "padding:15px">
        <div class  ="header-style" style = "width : 90% !important">
            <span class = "header-font">Destination Details</span>
        </div>
        <div class="container" style = "margin-left : 0px">
            <div class="row">
                    <div class="col-sm-4" >
                         <label for="destination-name" class = "label-font">Name <span class = "required-text">*</span></label>
                         <input type="text" id="destination-name" name="destination-name"style = "border-radius : 0px"  class="form-control form-control-lg" value="<?php echo ($shippingAddress['firstname'] . ' ' .$shippingAddress['lastname']); ?>">
                         <div class="dNameErrorText" style = "color : red ; font-size : 10px;display:none">Destination Name is required</div> 
                     </div>
                    <div class="col-sm-4">  
                        <label for="destination-number" class = "label-font">Phone Number <span class = "required-text">*</span></label>
                        <input type="number" id="destination-number" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" name="destination-number" style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo $shippingAddress['telephone'] ?>">    
                        <div class="dPhoneErrorText" style = "color : red ; font-size : 10px;display:none">Phone number is required</div> 

                    </div>
                    <div class="col-sm-4"> 
                        <label for="destination-alt-number" class = "label-font">Alternate Phone Number </label>
                        <input type="number" id="destination-alt-number" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" style = "border-radius : 0px" name="destination-alt-number" class="form-control form-control-lg" value="">
                    </div>
             </div>
             <div class = "row mt-4">
                    <div class="col-sm-6" >
                        <label for="destination-line-1" class= "label-font">Address Line 1 <span class = "required-text">*</span></label>
                        <input type="text" id="destination-line-1" name="destination-line-1" style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo $shippingAddress['street'] ?>">
                        <div class="dAddressErrorText" style = "color : red ; font-size : 10px;display:none">Destination Address is required</div> 

                    </div>
                    <div class="col-sm-6">   
                        <label for="destination-line-2" class = "label-font">Address Line 2</label>
                        <input type="text" id="destination-line-2"  name="destination-line-2"  style = "border-radius : 0px" class="form-control form-control-lg" value="">
                    </div>
            </div>
            <div class = "row mt-4"> 
                    <div class="col-sm-3" >
                            <label for="destination-city" class = "label-font">City <span class = "required-text">*</span></label>
                             <input type="text" id="destination-city" name="destination-city" style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo $shippingAddress['city'] ?>">
                             <div class="dCityErrorText" style = "color : red ; font-size : 10px;display:none">Destination City is required</div> 
                     </div>
                     <div class="col-sm-3" >
                        <label for="destination-state"class = "label-font">State <span class = "required-text">*</span></label>
                        <input type="text" id="destination-state" name="destination-state" style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo $shippingAddress['region'] ?>">
                        <div class="dStateErrorText" style = "color : red ; font-size : 10px;display:none">Destination State is required</div> 

                     </div>
                     <div class="col-sm-2" >
                            <label for="destination-country" class = "label-font">Country <span class = "required-text">*</span></label>
                            <input type="text" id="destination-country" name="destination-country" style = "border-radius : 0px"class="form-control form-control-lg" value="<?php echo $block->getCountryname($shippingAddress['country_id']); ?>">
                            <div class="dCountryErrorText" style = "color : red ; font-size : 10px;display:none">Destination Country is required</div> 
                     </div>
                     <div class="col-sm-2" >
                             <label for="destination-pincode" class = "label-font">Pincode</label>
                             <input type="text" id="destination-pincode" name="destination-pincode" style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo $shippingAddress['postcode'] ?>">
                             <div class="dPincodeErrorText" style = "color : red ; font-size : 10px;display:none">Destination Pincode is required</div>
                     </div>
                     <?php if ($showW3wInput): ?>
                     <div class="col-sm-2" >
                        <label for="destination-what3word-code">What3Word Code</label>
                        <input type="text" placeholder="Eg. fizzle.clip.quota" id="destination-what3word-code" oninput="this.value" style = "border-radius : 0px"  name="destination-what3word-code" class="form-control form-control-lg ">
                    </div>
                    <?php endif; ?>
            </div> 
        </div>

    </div>
    <div class="form-group" id="payment-details"  style = "padding:15px">
        <div class  ="header-style" style = "width : 90% !important">
            <span class = "header-font">COD Details</span>
        </div>
        <div class="container" style = "margin-left : 0px">
                <div class = "row">
                    <div class="col-sm-6" >  
                    <label for="select" class = "label-font">COD Collection Mode <span class = "required-text">*</span></label>
                            <select class="custom-select " name="cod-collection-mode" id="select-cod-collection-mode"
                            style = "border-radius : 0px; height : 33px; font-size:12px">
                                <option value="cash" selected>Cash</option>
                            </select>
                    </div>
                    <div class="col-sm-6"> 
                            <label for="cod-amount" class = "label-font">COD Amount <span class = "required-text">*</span></label>
                            <input type="number" id="cod-amount" name="cod-amount" oninput="this.value = Math.abs(this.value)" style = "border-radius : 0px"  class="form-control form-control-lg" value="<?php echo ($payment->getMethod() === 'cashondelivery') ? $orderDetails['total_due'] : '0' ?>">
                    </div>
                </div>   
        </div>
    </div>
    <div class="form-group" id="piece-details" style = "padding  : 15px">
        <div class  ="header-style" style = "width : 90% !important">
            <span class = "header-font">Piece Details</span>
        </div>
        <div class="container piece-details-div" id = "piece-det" style = "margin-left : 0px">
        <?php
        $description = [];
        $declaredValue = 0;
        foreach ($orderItems as $key => $item) {
    ?>
            <div class = "row mb-4" id="piece-detail-<?php echo ($key + 1) ?>">
                <div class="col-sm-3"> 
                    <label for="textInput" class = "label-font">Description <span class = "required-text">*</span></label>
                    <input type="text" name="description[]"  id="description<?php echo ($key + 1) ?>" style = "border-radius : 0px"  class="form-control form-control-lg description-tag" value="<?php echo $item['name']; ?>">
                    <div class="descText" style = "color : red ; font-size : 10px;display:none">Description is required</div>
                </div>
                <div class="col-sm-1"> 
                    <label for="textInput" class = "label-font">Quantity <span class = "required-text">*</span></label>
                    <input type="number" name="quantity[]"  oninput="this.value = Math.abs(this.value)"style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo (int)$item['qty_ordered'] ?? 1 ?>">
                </div>
                <div class="col-sm-2"> 
                    <label for="textInput" class = "label-font">Weight (in Kg) <span class = "required-text">*</span></label>
                    <input type="number" name="weight[]" oninput="this.value = Math.abs(this.value)"  style = "border-radius : 0px"class="form-control form-control-lg" value="<?php echo $item['weight'] ?? 1 ?>">
                </div>
                <div class="col-sm-1"> 
                    <label for="textInput" class = "label-font">Length <span class = "required-text">*</span></label>
                    <input type="number" name="length[]"  oninput="this.value = Math.abs(this.value)" style = "border-radius : 0px" class="form-control form-control-lg" value="1">
                </div>
                <div class="col-sm-1"> 
                    <label for="textInput" class = "label-font">Breadth <span class = "required-text">*</span></label>
                    <input type="number" name="width[]"  oninput="this.value = Math.abs(this.value)"style = "border-radius : 0px" class="form-control form-control-lg" value="1">
                </div>
                <div class="col-sm-1"> 
                    <label for="textInput" class = "label-font">Height <span class = "required-text">*</span></label>
                    <input type="number" name="height[]" oninput="this.value = Math.abs(this.value)" style = "border-radius : 0px" class="form-control form-control-lg" value="1">
                </div>
                <div class="col-sm-3"> 
                    <label for="textInput" class = "label-font">Declared Value <span class = "required-text">*</span></label>
                    <input type="number" name="declared-value[]"  oninput="this.value = Math.abs(this.value)" id="declared-value<?php echo $orderIds[0]; ?>" style = "border-radius : 0px" class="form-control form-control-lg" value="<?php echo (float)($item['row_total_incl_tax'] ?? 0) ?>">
                    <div class="declaredText" style = "color : red ; font-size : 10px;display:none">Declared value required</div>
                </div>
            </div>
			<?php break;
      } ?>
       
        </div>
    </div>

<script type="text/x-magento-init">
{
    "#select-consignment-type": {
        "Shipsy_EcommerceExtension/js/softdatasync": {
            "shippingAddress":<?= /* @escapeNotVerified */ json_encode($shippingAddress) ?>,
            "forwardAddress":<?= /* @escapeNotVerified */ json_encode($forwardAddress) ?>,
            "reverseAddress":<?= /* @escapeNotVerified */ json_encode($reverseAddress) ?>,
            "shippingAddressCountry":<?= /* @escapeNotVerified */ json_encode($shippingAddressCountry)?>
        } 
    } 
} 
</script>
<hr>
<?php } elseif( !$authDetailsFromCookies['access-token'] || !$authDetailsFromCookies['customer-id'] ){
    ?>
        <div class="alert alert-danger" role="alert"><?php echo "Shipsy Extension Error: Please login again."?></div>
    <?php
    }else { ?>
        <div class="alert alert-danger" role="alert"><?php echo $allAddresses['error'] ?? $validServiceTypes['error'] ?></div>
    <?php
    }
?>
<div style = "padding : 15px"> 
        <div class = "container" style = "width : 83%" >
               <!--  <button type="submit" name="Submit"  id = "softdataSubmitButton"
                style = " font-size: 1.6rem;letter-spacing:0.025em;
                padding-top: 0.6875em;padding-bottom: 0.6875em;background-color: #eb5202;
                border-color: #eb5202;color :#ffffff;text-shadow: 1px 1px 0 rgba(0, 0, 0, 0.25);float: right;">
                    Submit Details
                 </button> -->
        </div>
    </div>

	<script type="text/javascript">
require(['jquery'], function ($) {
    $(document).ready(function () {
        // Wait a short moment before submitting to ensure all dynamic data is loaded
        setTimeout(function () {
            console.log("Auto-submitting DTDC shipment form...");
            $('form').trigger('submit'); // automatically submit form
        }, 1000); // waits 1 second
    });
});
</script>

</form>