<?php
    $response = $block->getAddresses();
    $authDetailsFromCookies = $block->getAuthDetailsFromCookies();
if (array_key_exists('data', $response) && !empty($response['data'])) {
    $allAddresses = $response['data'];
    $forwardAddress = (array_key_exists('forwardAddress', $allAddresses)) ? $allAddresses['forwardAddress'] : [];
    $reverseAddress = (array_key_exists('reverseAddress', $allAddresses)) ? $allAddresses['reverseAddress'] : [];
    $exceptionalReturnAddress = (array_key_exists('exceptionalReturnAddress', $allAddresses)) ? $allAddresses['exceptionalReturnAddress'] : [];
    $showW3wInput = $block->getW3wConfig() == '1';
    ?>

<form action="<?php echo $block->getUrl('softdatasync/setup/formdata'); ?>" method="post" >
<input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>" />
    <div class="form-group" id="forward-address" style = "padding  : 15px">
        <div class  ="header-style">
            <span class = "header-font">Forward Details</span>
        </div>
        <div class="container-fluid" style = "margin-left : 0px">
            <div class = "row">
                <div class = "col-sm-4">
                    <label for="forward-name" class = "label-font">Name <span class = "required-text">*</span></label>
                    <input type="text" id="forward-name" name="forward-name" class="form-control form-control-lg" style= "border-radius:0px" value="<?php echo $forwardAddress['name'] ?? '' ?>" required>
                    <div class="nameErrorText" style = "color : red ; font-size : 10px;display:none">Name is required</div>
                </div> 
                <div class = "col-sm-3">
                    <label for="forward-phone" class = "label-font">Phone Number <span class = "required-text">*</span></label>
                    <input type="number" id="forward-phone" name="forward-phone" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10"  style= "border-radius:0px"class="form-control form-control-lg" value="<?php echo $forwardAddress['phone'] ?? '' ?>">
                    <div class="phoneErrorText" style = "color : red ; font-size : 10px;display:none">Phone Number is required</div>
                </div> 
                <div class = "col-sm-3">
                    <label for="forward-alt-phone" class = "label-font">Alternate Phone Number</label>
                    <input type="number" id="forward-alt-phone" name="forward-alt-phone" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['alternate_phone'] ?? '' ?>"> 
                </div> 
                <div class = "col-sm-2"></div> 
            </div>
            <div class = "row mt-4">
                <div class = "col-sm-5">
                    <label for="forward-line-1" class = "label-font">Address Line 1 <span class = "required-text">*</span></label>
                    <input type="text" id="forward-line-1" name="forward-line-1"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['address_line_1'] ?? '' ?>">
                    <div class="addressErrorText" style = "color : red ; font-size : 10px;display:none">Address is required</div>
                </div>
                <div class = "col-sm-5"> 
                    <label for="forward-line-2" class = "label-font">Address Line 2</label>
                     <input type="text" id="forward-line-2" name="forward-line-2"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['address_line_2'] ?? '' ?>">
                </div>
                <div class = "col-sm-2"> </div>
            </div>
            <div class  ="row mt-4">
                <div class = "col-sm-2">
                    <label for="forward-city" class = "label-font">City</label>
                     <input type="text" id="forward-city" name="forward-city"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['city'] ?? '' ?>">
                    </div>
                <div class = "col-sm-3">
                    <label for="forward-state" class = "label-font">State</label>
                     <input type="text" id="forward-state" name="forward-state"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['state'] ?? '' ?>">
                </div>
                <div class = "col-sm-2">
                    <label for="forward-country" class = "label-font">Country</label>
                    <input type="text" id="forward-country" name="forward-country"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['country'] ?? '' ?>">
                </div>
                <div class = "col-sm-2">
                    <label for="forward-pincode" class = "label-font">Pincode</label>
                    <input type="text" id="forward-pincode" name="forward-pincode"style= "border-radius:0px"  class="form-control form-control-lg" value="<?php echo $forwardAddress['pincode'] ?? '' ?>">
                </div>
                <?php if ($showW3wInput): ?>
                        <div class="col-sm-3">
                            <label for="forward-what3word-code">What3Word Code</label>
                            <input type="text" placeholder="Eg. fizzle.clip.quota" id="forward-what3word-code"
                                oninput="this.value" style="border-radius : 0px" name="forward-what3word-code"
                                class="form-control form-control-lg " value="<?php echo $forwardAddress['w3w_code'] ?? '' ?>">
                        </div>
                <?php endif; ?>
            </div>
        </div>

    </div>
    <div class="form-group" id="reverse-address" style = "padding : 15px">
        <div class  ="header-style">
            <span class = "header-font">Reverse Details</span>
        </div>

        <div class="container-fluid" style = "margin-left : 0px">
            <div class = "row">
                <div class = "col-sm-4">
                    <label for="reverse-name" class = "label-font">Name <span class = "required-text">*</span></label>
                    <input type="text" id="reverse-name" name="reverse-name" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['name'] ?? '' ?>">
                    <div class="rNameErrorText" style = "color : red ; font-size : 10px;display:none">Name is required</div>

                </div> 
                <div class = "col-sm-3">

                     <label for="reverse-phone" class = "label-font">Phone Number <span class = "required-text">*</span></label>
                    <input type="number" id="reverse-phone" name="reverse-phone" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['phone'] ?? '' ?>">
                    <div class="rPhoneErrorText" style = "color : red ; font-size : 10px;display:none">Phone number is required</div>

                </div> 
                <div class = "col-sm-3">
                    <label for="reverse-alt-phone"class = "label-font">Alternate Phone Number</label>
                    <input type="number" id="reverse-alt-phone" name="reverse-alt-phone" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10"  style = "border-radius:0px"class="form-control form-control-lg" value="<?php echo $reverseAddress['alternate_phone'] ?? '' ?>">
                </div> 
                <div class = "col-sm-2"></div> 
            </div>
            <div class = "row mt-4">
                <div class = "col-sm-5">
                    <label for="reverse-line-1" class = "label-font">Address Line 1 <span class = "required-text">*</span></label>
                    <input type="text" id="reverse-line-1" name="reverse-line-1" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['address_line_1'] ?? '' ?>">
                    <div class="rAddressErrorText" style = "color : red ; font-size : 10px;display:none">Address is required</div>

                </div>
                <div class = "col-sm-5"> 
                    <label for="reverse-line-2" class = "label-font">Address Line 2</label>
                    <input type="text" id="reverse-line-2" name="reverse-line-2" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['address_line_2'] ?? '' ?>">
                </div>
                <div class = "col-sm-2"> </div>
            </div>
            <div class  ="row mt-4">
                <div class = "col-sm-2">
                    <label for="reverse-city" class = "label-font">City </label>
                     <input type="text" id="reverse-city" name="reverse-city" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['city'] ?? '' ?>">
                </div>
                <div class = "col-sm-3">
                        <label for="reverse-state" class = "label-font"> State </label>
                        <input type="text" id="reverse-state" name="reverse-state" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['state'] ?? '' ?>">
                </div>
                <div class = "col-sm-2">
                    <label for="reverse-country" class = "label-font">Country </label>
                     <input type="text" id="reverse-country" name="reverse-country" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['country'] ?? '' ?>">
                </div>
                <div class = "col-sm-2">
                    <label for="reverse-pincode" class = "label-font"> Pincode </label>
                     <input type="text" id="reverse-pincode" name="reverse-pincode"  style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $reverseAddress['pincode'] ?? '' ?>">
                </div>
                <?php if ($showW3wInput): ?>
                        <div class="col-sm-3">
                            <label for="reverse-what3word-code">What3Word Code</label>
                            <input type="text" placeholder="Eg. fizzle.clip.quota" id="reverse-what3word-code"
                                oninput="this.value" style="border-radius : 0px" name="reverse-what3word-code"
                                class="form-control form-control-lg " value="<?php echo $reverseAddress['w3w_code'] ?? '' ?>">
                        </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="form-group" style = "padding : 15px;margin-left : 3px">
        <div class=" container-fluid">
            <div class  ="row">
                <div class = " form-check col-sm-3">
                <input class="form-check-input"  style = "border-radius : 0px" type="checkbox" name="useForwardCheck" value="true" id="useForwardCheck">
                <label class="form-check-label" for="useForwardCheck" style = "margin-left:10px">Use Forward Address for Reverse</label>
                </div>
                <div class = "col-sm-9"></div>
            </div>
        </div>
    </div>

    <div class="form-group" id="exp-reverse-address" style = "padding  : 15px">
        <div class  ="header-style">
            <span class = "header-font">Exceptional Return Details</span>
        </div>
        <div class="container-fluid" style = "margin-left : 0px">
            <div class = "row">
                <div class = "col-sm-4">
                    <label for="exp-return-name" class = "label-font">Name <span class = "required-text">*</span></label>
                    <input type="text" id="exp-return-name" name="exp-return-name" style = "border-radius:0px" class="form-control form-control-lg" value="<?php echo $exceptionalReturnAddress['name'] ?? '' ?>">
                    <div class="eNameErrorText" style = "color : red ; font-size : 10px;display:none">Name is required</div>
                </div> 
                <div class = "col-sm-3">
                    <label for="exp-return-phone" class = "label-font">Phone Number <span class = "required-text">*</span></label>
                    <input type="number" id="exp-return-phone" name="exp-return-phone" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['phone'] ?? '' ?>">
                    <div class="ePhoneErrorText" style = "color : red ; font-size : 10px;display:none">Phone number is required</div>
                </div> 
                <div class = "col-sm-3">
                    <label for="exp-return-alt-number" class = "label-font">Alternate Phone Number</label>
                    <input type="number" id="exp-return-alt-phone" name="exp-return-alt-phone" oninput="this.value=this.value.slice(0,this.maxLength)" maxlength="10" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['alternate_phone'] ?? '' ?>">
                </div> 
                <div class = "col-sm-2"></div> 
            </div>
            <div class = "row mt-4">
                <div class = "col-sm-5">
                    <label for="exp-return-line-1" class = "label-font">Address Line 1 <span class = "required-text">*</span></label>
                    <input type="text" id="exp-return-line-1" name="exp-return-line-1" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['address_line_1'] ?? '' ?>">
                    <div class="eAddressErrorText" style = "color : red ; font-size : 10px;display:none">Address is required</div>
                </div>
                <div class = "col-sm-5"> 
                    <label for="exp-return-line-2" class = "label-font">Address Line 2</label>
                    <input type="text" id="exp-return-line-2" name="exp-return-line-2" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['address_line_2'] ?? '' ?>">
                </div>
                <div class = "col-sm-2"> </div>
            </div>
            <div class  ="row mt-4">
                <div class = "col-sm-2">
                    <label for="exp-return-city" class = "label-font">City </label>
                    <input type="text" id="exp-return-city" name="exp-return-city" style = "border-radius:0px"class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['city'] ?? '' ?>">
                </div>
                <div class = "col-sm-3">
                    <label for="exp-return-state" class = "label-font">State </label>
                    <input type="text" id="exp-return-state" name="exp-return-state" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['state'] ?? '' ?>">
                </div>
                <div class = "col-sm-2">
                    <label for="exp-return-country" class = "label-font">Country </label>
                     <input type="text" id="exp-return-country" name="exp-return-country" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['country'] ?? '' ?>">
                    </div>
                <div class = "col-sm-2">
                    <label for="exp-return-pincode" class = "label-font">Pincode </label>
                    <input type="text" id="exp-return-pincode" name="exp-return-pincode" style = "border-radius:0px" class="form-control form-control-lg"" value="<?php echo $exceptionalReturnAddress['pincode'] ?? '' ?>">
                </div>
                <?php if ($showW3wInput): ?>
                        <div class="col-sm-3">
                            <label for="exp-return-what3word-code">What3Word Code</label>
                            <input type="text" placeholder="Eg. fizzle.clip.quota" id="exp-return-what3word-code"
                                oninput="this.value" style="border-radius : 0px" name="exp-return-what3word-code"
                                class="form-control form-control-lg " value="<?php echo $exceptionalReturnAddress['w3w_code'] ?? '' ?>">
                        </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div style = "padding:15px" >
        <div class = "container-fluid" style = "margin-left:0px">
            <div class = "row">
                <div class = "col-sm-11" id = "setup-form" >
                    <button type="submit" name="Submit" id = "setupSubmitButton" disabled = 'disabled'>Submit Details</button>
                </div>
            </div>
        </div>
    </div>
</form>
    <?php
} elseif( !$authDetailsFromCookies['access-token'] || !$authDetailsFromCookies['customer-id'] ){
    ?>
        <div class="alert alert-danger" role="alert"><?php echo "Shipsy Extension Error: Please login again."?></div>
    <?php
} 
else { ?>
        <div class="alert alert-danger" role="alert"><?php echo $response['error']['message']?></div>
    <?php
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "Shipsy_EcommerceExtension/js/address": {}
    }
}
</script>