<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$stripSelection = $product->getConfigureMode() ? true : false;
$options = $block->decorateArray($block->getOptions($stripSelection));


?>
<?php if ($product->isSaleable()):?>
    <?php if (count($options)): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }
</script>
        <div class="bundle-customize-title"><?= /* @escapeNotVerified */ __('Customize: %1', $helper->productAttribute($product, $product->getName(), 'name')) ?></div>
        <fieldset class="fieldset fieldset-bundle-options">
            <?= $block->getChildHtml('product_info_bundle_options_top') ?>
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?= $block->getOptionHtml($option) ?>
            <?php endforeach; ?>
            <h2 id="finalPrice"></h2>
        </fieldset>

    <?php else: ?>
        <p class="empty"><?= /* @escapeNotVerified */ __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
<script type="text/javascript">
require(['jquery'], function(jquery) {
    jquery(document).ready(function($){
         /** Do Something **/
         var a = $('.options-list h2').text();

         $('#finalPrice').text('Rs.'+a);

         $("input[type='radio']").click(function(){

            var radioValue = $('.options-list[name="option-list-name"] .choice :checked').siblings('label').children('span').find('span.price').text().substring(1);
            var add = Number(radioValue)+Number(a);
            $('#finalPrice').text('Rs.'+add+'.00');
        });

        var id = $('.fieldset-bundle-options select').attr('id');
        console.log($('#'+id).val());

        $('#'+id).on('change', function(){ 
            var array;
            array = $(this).val();
            var price = 0;
            $.each(array, function(index, value){
                var index = $('#'+id).find('option[value="'+value+'"]').text().indexOf('$');
                var newPrice = $('#'+id).find('option[value="'+value+'"]').text().substring(index+1);
                price+=Number(newPrice);
            });
            console.log(price);
             var add = Number(price)+Number(a);
            $('#finalPrice').text('Rs.'+add+'.00');
        });

    });
});
</script>