<script type="text/javascript">
    requirejs([ 'jquery' ], function ($) {
            $(document).ready(function() {
                //update URLs for help center menu items
                $('.item-helpcenter .item-docs a').attr('href', 'https://www.ubertheme.com/docs').attr('target', '_blank');
                $('.item-helpcenter .item-support a').attr('href', 'https://www.ubertheme.com/ask-question').attr('target', '_blank');
                $('.item-helpcenter .item-marketplace a').attr('href', 'https://www.ubertheme.com/magento-extensions-2-x').attr('target', '_blank');
            });
        });
</script>