<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Details
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();

$att_sku = $_product->getAttributeText('sku');
$att_publisher = $_product->getAttributeText('prod_attr_publisher');
$att_prod_title = $_product->getAttributeText('title');
$att_weight = $_product->getAttributeText('weight');
// $_product->getResource()->getAttribute($_code)->getFrontendLabel()
?>
<section id="product-details-tab">
<table class="table table-striped">
    <caption><?= /* @escapeNotVerified */ __('Features') ?></caption>
  <tbody>
    <tr>
        <td class="col label" scope="row"></td>
    </tr>
    </tbody>
</table>
</section>



